/**
 * The browser-safe schemas of `@lore/deploy`, Lore as Vercel: apps, telemetry (sigils, analytics, vitals, blights, quality), deployments and estates.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export { appInstances } from "../api/entities/appInstances.ts";
export { appSecrets } from "../api/entities/appSecrets.ts";
export { artifacts } from "../api/entities/artifacts.ts";
export { blights } from "../api/entities/blights.ts";
export { deployments } from "../api/entities/deployments.ts";
export { estateCommands } from "../api/entities/estateCommands.ts";
export { estateInventories } from "../api/entities/estateInventories.ts";
export { estateProjects } from "../api/entities/estateProjects.ts";
export { type Estate, estates } from "../api/entities/estates.ts";
export { qualityRuns } from "../api/entities/qualityRuns.ts";
export { sigilErrorGroups } from "../api/entities/sigilErrorGroups.ts";
export {
  UNIQUES_COLLAPSED_HASH,
  sigilUniquesDaily,
} from "../api/entities/sigilUniquesDaily.ts";
export { type Sigil, sigils } from "../api/entities/sigils.ts";
export type { AdminEstateResource } from "../api/schemas/adminEstateResourceSchema.ts";
export type { AppInstanceResource } from "../api/schemas/appInstanceResourceSchema.ts";
export { appsCapabilityOptionsSchema } from "../api/schemas/appsCapabilityOptionsSchema.ts";
export {
  CLOUDFLARE_TOKEN_TEMPLATE,
  cloudflareTokenTemplateUrl,
} from "../api/schemas/cloudflareTokenTemplate.ts";
export { createEstateBodySchema } from "../api/schemas/createEstateBodySchema.ts";
export { defaultAppInstance } from "../api/schemas/defaultAppInstance.ts";
export { estateClientFrameSchema } from "../api/schemas/estateClientFrameSchema.ts";
export type { EstateCommandFrame } from "../api/schemas/estateCommandFrameSchema.ts";
export { estateCommandResultSchema } from "../api/schemas/estateCommandResultSchema.ts";
export type { EstateInventoryFrame } from "../api/schemas/estateInventoryFrameSchema.ts";
export {
  type EstateServerFrame,
  estateServerFrameSchema,
} from "../api/schemas/estateServerFrameSchema.ts";
export type { EstateStatsFrame } from "../api/schemas/estateStatsFrameSchema.ts";
export { insightsDimensionResourceSchema } from "../api/schemas/insightsDimensionResourceSchema.ts";
export type { QualityRunPush } from "../api/schemas/qualityRunPushSchema.ts";

// The dashboard metrics' declarative half: both runtimes register it.
export { DeployDashboardMetrics } from "../api/services/DeployDashboardMetrics.ts";
