/**
 * The browser-safe schemas of `@lore/deploy`, Lore as Vercel: apps, telemetry (sigils, analytics, vitals, blights, quality), deployments and estates.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export {
  type AppInstance,
  type AppInstanceInsert,
  appInstances,
} from "../api/entities/appInstances.ts";
export { type AppSecret, appSecrets } from "../api/entities/appSecrets.ts";
export { type Artifact, artifacts } from "../api/entities/artifacts.ts";
export {
  type BlightIgnoreRule,
  type BlightIgnoreRuleInsert,
  blightIgnoreRules,
} from "../api/entities/blightIgnoreRules.ts";
export {
  type Blight,
  type BlightInsert,
  blights,
} from "../api/entities/blights.ts";
export { type Deployment, deployments } from "../api/entities/deployments.ts";
export {
  type EstateCommand,
  estateCommands,
} from "../api/entities/estateCommands.ts";
export {
  type EstateInventory,
  estateInventories,
} from "../api/entities/estateInventories.ts";
export {
  type EstateProject,
  estateProjects,
} from "../api/entities/estateProjects.ts";
export {
  ESTATE_TYPES,
  type Estate,
  type EstateInsert,
  type EstateType,
  estates,
} from "../api/entities/estates.ts";
export { type QualityRun, qualityRuns } from "../api/entities/qualityRuns.ts";
export {
  type SigilErrorGroup,
  type SigilErrorGroupInsert,
  sigilErrorGroups,
} from "../api/entities/sigilErrorGroups.ts";
export {
  type SigilUniqueDaily,
  type SigilUniqueDailyInsert,
  UNIQUES_COLLAPSED_HASH,
  sigilUniquesDaily,
} from "../api/entities/sigilUniquesDaily.ts";
export {
  SIGIL_KINDS,
  type Sigil,
  type SigilInsert,
  type SigilKind,
  sigils,
} from "../api/entities/sigils.ts";
export { acceptedRuntimes } from "../api/schemas/acceptedRuntimes.ts";
export {
  type AdminEstateResource,
  adminEstateResourceSchema,
} from "../api/schemas/adminEstateResourceSchema.ts";
export {
  type AppInstanceResource,
  appInstanceResourceSchema,
} from "../api/schemas/appInstanceResourceSchema.ts";
export { appSecretResourceSchema } from "../api/schemas/appSecretResourceSchema.ts";
export {
  type AppsCapabilityOptions,
  appsCapabilityOptionsSchema,
} from "../api/schemas/appsCapabilityOptionsSchema.ts";
export {
  ARTIFACT_FORMATS,
  type ArtifactFormat,
  artifactFormatSchema,
} from "../api/schemas/artifactFormatSchema.ts";
export {
  type ArtifactGroup,
  artifactGroupSchema,
} from "../api/schemas/artifactGroupSchema.ts";
export {
  type ArtifactList,
  artifactListSchema,
} from "../api/schemas/artifactListSchema.ts";
export {
  type ArtifactManifest,
  artifactManifestSchema,
} from "../api/schemas/artifactManifestSchema.ts";
export {
  type ArtifactPushResult,
  artifactPushResultSchema,
} from "../api/schemas/artifactPushResultSchema.ts";
export {
  type ArtifactResource,
  artifactResourceSchema,
} from "../api/schemas/artifactResourceSchema.ts";
export { QUEST_STATUS_PREFIX } from "../api/schemas/blightQuestStatus.ts";
export {
  type BlightResource,
  blightResourceSchema,
} from "../api/schemas/blightResourceSchema.ts";
export {
  type BlightRuleResource,
  blightRuleResourceSchema,
} from "../api/schemas/blightRuleResourceSchema.ts";
export { blightSigilSchema } from "../api/schemas/blightSigilSchema.ts";
export {
  CLOUDFLARE_ACCOUNT_ID_PATTERN,
  cloudflareAccountIdSchema,
  cloudflareTokenSchema,
} from "../api/schemas/cloudflareCredentialSchema.ts";
export {
  CLOUDFLARE_TOKEN_TEMPLATE,
  type CloudflareTokenTemplateRow,
  cloudflareTokenTemplateUrl,
} from "../api/schemas/cloudflareTokenTemplate.ts";
export {
  type CreateEstateBody,
  createEstateBodySchema,
} from "../api/schemas/createEstateBodySchema.ts";
export {
  type DeclaredEnvKey,
  declaredEnvKeySchema,
} from "../api/schemas/declaredEnvKeySchema.ts";
export { defaultAppInstance } from "../api/schemas/defaultAppInstance.ts";
export {
  type DeployAssetCacheEntry,
  deployAssetCacheSchema,
} from "../api/schemas/deployAssetCacheSchema.ts";
export {
  type EstateAckFrame,
  estateAckFrameSchema,
} from "../api/schemas/estateAckFrameSchema.ts";
export {
  type EstateClientFrame,
  estateClientFrameSchema,
} from "../api/schemas/estateClientFrameSchema.ts";
export {
  type EstateCommandFrame,
  estateCommandFrameSchema,
} from "../api/schemas/estateCommandFrameSchema.ts";
export {
  type EstateCommandPayload,
  estateCommandPayloadSchema,
} from "../api/schemas/estateCommandPayloadSchema.ts";
export {
  type EstateCommandListItem,
  type EstateCommandResource,
  estateCommandListItemSchema,
  estateCommandResourceSchema,
} from "../api/schemas/estateCommandResourceSchema.ts";
export {
  type EstateCommandResult,
  estateCommandResultSchema,
} from "../api/schemas/estateCommandResultSchema.ts";
export {
  ESTATE_COMMAND_KINDS,
  ESTATE_COMMAND_STATUSES,
  type EstateCommandKind,
  type EstateCommandStatus,
} from "../api/schemas/estateCommandValues.ts";
export {
  type EstateHelloFrame,
  estateHelloFrameSchema,
} from "../api/schemas/estateHelloFrameSchema.ts";
export {
  type EstateInventoryApp,
  estateInventoryAppSchema,
} from "../api/schemas/estateInventoryAppSchema.ts";
export {
  type EstateInventoryFrame,
  estateInventoryFrameSchema,
} from "../api/schemas/estateInventoryFrameSchema.ts";
export {
  type EstateInventoryHost,
  estateInventoryHostSchema,
} from "../api/schemas/estateInventoryHostSchema.ts";
export {
  type EstateInventoryExpectedApp,
  type EstateInventoryProject,
  type EstateInventoryReportedApp,
  type EstateInventoryResource,
  type EstateInventoryTracking,
  estateInventoryExpectedAppSchema,
  estateInventoryProjectSchema,
  estateInventoryReportedAppSchema,
  estateInventoryResourceSchema,
} from "../api/schemas/estateInventoryResourceSchema.ts";
export {
  type EstateQueryFrame,
  estateQueryFrameSchema,
} from "../api/schemas/estateQueryFrameSchema.ts";
export {
  type EstateResource,
  type MintedEstate,
  estateResourceSchema,
  mintedEstateSchema,
} from "../api/schemas/estateResourceSchema.ts";
export {
  type EstateServerFrame,
  estateServerFrameSchema,
} from "../api/schemas/estateServerFrameSchema.ts";
export {
  ESTATE_SLUG_MAX_LENGTH,
  ESTATE_SLUG_PATTERN,
  estateSlugSchema,
} from "../api/schemas/estateSlugSchema.ts";
export {
  type EstateStatsFrame,
  estateStatsFrameSchema,
} from "../api/schemas/estateStatsFrameSchema.ts";
export {
  ESTATE_PROTOCOL_VERSION,
  type EstateWelcomeFrame,
  estateWelcomeFrameSchema,
} from "../api/schemas/estateWelcomeFrameSchema.ts";
export {
  type InsightsDimensionResource,
  insightsDimensionResourceSchema,
} from "../api/schemas/insightsDimensionResourceSchema.ts";
export {
  type InsightsResource,
  insightsResourceSchema,
} from "../api/schemas/insightsResourceSchema.ts";
export {
  type LentEstateResource,
  type MintedLentEstate,
  lentEstateResourceSchema,
  mintedLentEstateSchema,
} from "../api/schemas/lentEstateResourceSchema.ts";
export {
  type OpenBlightsFilters,
  openBlightsFiltersSchema,
} from "../api/schemas/openBlightsFiltersSchema.ts";
export {
  type EstateInventorySummary,
  type EstateLoan,
  type OwnedEstateResource,
  estateInventorySummarySchema,
  estateLoanSchema,
  ownedEstateResourceSchema,
} from "../api/schemas/ownedEstateResourceSchema.ts";
export {
  type QualityOverview,
  qualityOverviewSchema,
} from "../api/schemas/qualityOverviewSchema.ts";
export {
  type QualityRunPush,
  qualityRunPushSchema,
} from "../api/schemas/qualityRunPushSchema.ts";
export {
  type QualityRunResource,
  qualityRunSchema,
} from "../api/schemas/qualityRunSchema.ts";
export { isAllowedRegistryHost } from "../api/schemas/registryHosts.ts";
export {
  type MintedSigil,
  type SigilResource,
  mintedSigilSchema,
  sigilResourceSchema,
} from "../api/schemas/sigilResourceSchema.ts";
export {
  type TrafficFilter,
  trafficFilterSchema,
} from "../api/schemas/trafficFilterSchema.ts";
export {
  type UniqueVisitorsFilters,
  uniqueVisitorsFiltersSchema,
} from "../api/schemas/uniqueVisitorsFiltersSchema.ts";
export {
  type VitalsMetricResource,
  vitalsMetricSchema,
} from "../api/schemas/vitalsMetricSchema.ts";
export {
  type VitalsPathsResource,
  vitalsPathsResourceSchema,
} from "../api/schemas/vitalsPathsResourceSchema.ts";
export {
  appInstanceCreateParamsSchema,
  appInstanceCreateResultSchema,
  appInstanceDeleteParamsSchema,
  appInstanceDeleteResultSchema,
  appInstanceGetParamsSchema,
  appInstanceGetResultSchema,
  appInstanceListParamsSchema,
  appInstanceListResultSchema,
  appInstanceUpdateParamsSchema,
  appInstanceUpdateResultSchema,
} from "../mcp/schemas/appInstanceSchemas.ts";
export {
  artifactGetParamsSchema,
  artifactGetResultSchema,
  artifactListParamsSchema,
  artifactListResultSchema,
} from "../mcp/schemas/artifactSchemas.ts";
export {
  blightForwardParamsSchema,
  blightForwardResultSchema,
  blightListParamsSchema,
  blightListResultSchema,
  blightResolveParamsSchema,
  blightResolveResultSchema,
} from "../mcp/schemas/blightSchemas.ts";
export {
  deployRollbackParamsSchema,
  deployRollbackResultSchema,
  deployStartParamsSchema,
  deployStartResultSchema,
  deployStatusParamsSchema,
  deployStatusResultSchema,
} from "../mcp/schemas/deploySchemas.ts";
export {
  insightsReadParamsSchema,
  insightsReadResultSchema,
} from "../mcp/schemas/insightsSchemas.ts";
export {
  sigilCreateParamsSchema,
  sigilCreateResultSchema,
  sigilDeleteParamsSchema,
  sigilDeleteResultSchema,
  sigilListParamsSchema,
  sigilListResultSchema,
  sigilRotateParamsSchema,
  sigilRotateResultSchema,
} from "../mcp/schemas/sigilSchemas.ts";

// The dashboard metrics' declarative half: both runtimes register it.
export { DeployDashboardMetrics } from "../api/services/DeployDashboardMetrics.ts";
