/**
 * The browser-safe schemas of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export { folioAttachments } from "../api/entities/folioAttachments.ts";
export { folioDirectories } from "../api/entities/folioDirectories.ts";
export { folioNames } from "../api/entities/folioNames.ts";
export { folioRevisions } from "../api/entities/folioRevisions.ts";
export { folios } from "../api/entities/folios.ts";
export { knowledgeCapabilityOptionsSchema } from "../api/schemas/knowledgeCapabilityOptionsSchema.ts";
