/**
 * The browser-safe schemas of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export {
  type FolioAttachment,
  folioAttachments,
} from "../api/entities/folioAttachments.ts";
export {
  type FolioDirectory,
  folioDirectories,
} from "../api/entities/folioDirectories.ts";
export { type FolioName, folioNames } from "../api/entities/folioNames.ts";
export {
  type FolioRevision,
  folioRevisions,
} from "../api/entities/folioRevisions.ts";
export {
  type Folio,
  buildFolioSearchText,
  folios,
} from "../api/entities/folios.ts";
export { folioIdParamsSchema } from "../api/schemas/folioIdParamsSchema.ts";
export { folioListQuerySchema } from "../api/schemas/folioListQuerySchema.ts";
export {
  type FolioLinks,
  type FolioMetadata,
  type FolioPath,
  type FolioResource,
  folioLinksSchema,
  folioResourceSchema,
} from "../api/schemas/folioResourceSchema.ts";
export {
  type FolioRow,
  folioRowSchema,
} from "../api/schemas/folioRowSchema.ts";
export { folioSavedSchema } from "../api/schemas/folioSavedSchema.ts";
export {
  type FolioTreeEntry,
  folioTreeEntrySchema,
} from "../api/schemas/folioTreeEntrySchema.ts";
export {
  type HydratedFolioAttachment,
  hydratedFolioAttachmentSchema,
} from "../api/schemas/hydratedFolioAttachmentSchema.ts";
export {
  type KnowledgeCapabilityOptions,
  knowledgeCapabilityOptionsSchema,
} from "../api/schemas/knowledgeCapabilityOptionsSchema.ts";
export {
  folioEpicRefSchema,
  folioFullSchema,
  folioRefParamsSchema,
  folioRefSchema,
} from "../mcp/schemas/folioSchemas.ts";
