import { AccountRouter, accountRouterOptionsAtom } from "@alepha/ui/account";
import { $module } from "alepha";
import { AlephaCrypto } from "alepha/crypto";
import { AlephaReactAuth } from "alepha/react/auth";
import { I18nProvider } from "alepha/react/i18n";
import { AlephaReactUi } from "alepha/react/ui";
import { createElement, lazy, Suspense } from "react";

import { currentProjectAtom } from "./app/atoms/currentProjectAtom.ts";
import { currentProjectMemberAtom } from "./app/atoms/currentProjectMemberAtom.ts";
import { projectPromptsAtom } from "./app/atoms/projectPromptsAtom.ts";
import { userProjectsAtom } from "./app/atoms/userProjectsAtom.ts";
import AccountDeleteWarning from "./app/components/account/AccountDeleteWarning.tsx";
import { LoreAccountRouter } from "./app/components/account/LoreAccountRouter.ts";
import { CoreRouter } from "./app/CoreRouter.ts";
import { I18n } from "./app/services/I18n.ts";
import { ThemesProvider } from "./app/services/ThemesProvider.ts";

/**
 * The browser-safe half of `@lore/core`, the glue: projects, capabilities, ranks and permissions, notifications, audits, the resource registry and its link graph, search, the dashboard, reports, agent prompts and the web shell: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreCoreWeb = $module({
  name: "lore.core.web",
  // `AlephaReactAuth` explicitly: the sign-in, register and verification
  // pages need `ReactAuth`, and nothing on the page tree injects it any more
  // (the old `AppRouter` held an unused field that registered it, #E75).
  imports: [AlephaReactUi, AlephaCrypto, AlephaReactAuth],
  atoms: [
    currentProjectAtom,
    currentProjectMemberAtom,
    projectPromptsAtom,
    userProjectsAtom,
  ],
  register(alepha) {
    // Injected here rather than listed in `services`: a listed service is
    // tagged with this module, and injecting it anywhere then registers the
    // whole module, router included. This module's barrel is what every
    // component imports from, so a spec rendering one `AccountRouter` page,
    // or reading the dictionaries, would boot Lore's whole page tree.
    alepha.inject(I18n);
    alepha.inject(ThemesProvider);
    alepha.inject(CoreRouter);
    alepha.inject(AccountRouter);
    alepha.inject(LoreAccountRouter);

    // Lore's `quests.createdBy` cascades, so deleting an account also deletes
    // every quest it authored, including inside other people's projects. The
    // framework cannot know that; this fills the dialog's warning slot so the
    // consequences are stated before the click rather than discovered after
    // it, each module's line registered on `AccountDeletionRegistry`.
    //
    // `/account` is a root shell like `/admin` (#E68): not adopted into
    // `CoreRouter.layout`, so its chrome is set here. The brand is Lore's
    // mark linking home, loaded lazily so the account chrome stays out of
    // the bundle every page loads; `Suspense` holds the header empty for the
    // moment the chunk takes.
    alepha.store.set(accountRouterOptionsAtom, {
      brand: createElement(
        Suspense,
        { fallback: null },
        createElement(
          lazy(() => import("./app/components/account/LoreAccountBrand.tsx")),
        ),
      ),
      homeRouteName: "home",
      pages: {
        security: { deleteWarning: createElement(AccountDeleteWarning) },
      },
    });

    // Dogfood locale-prefix routing: French gets `/fr/...` URLs, English (the
    // default) stays unprefixed. Source of truth is the URL, with hreflang
    // alternates emitted for SEO.
    alepha.inject(I18nProvider).options.routing = "prefix";
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { $pageProject, $pageProjectSettings } from "./app/$pageProject.ts";
export { CoreRouter } from "./app/CoreRouter.ts";
export { currentProjectAtom } from "./app/atoms/currentProjectAtom.ts";
export { currentProjectMemberAtom } from "./app/atoms/currentProjectMemberAtom.ts";
export {
  type ProjectNavEntry,
  projectNavAtom,
} from "./app/atoms/projectNavAtom.ts";
export { projectPromptsAtom } from "./app/atoms/projectPromptsAtom.ts";
export { userProjectsAtom } from "./app/atoms/userProjectsAtom.ts";
export { LoreAccountRouter } from "./app/components/account/LoreAccountRouter.ts";
export { isOAuthReturnTarget } from "./app/components/auth/oauthReturnTarget.ts";
export { type DashboardScopeApp } from "./app/components/dashboard/DashboardScopeStep.tsx";
export {
  eligibleApps,
  eligibleProjects,
  metricUnavailableKey,
} from "./app/components/dashboard/dashboardEligibility.ts";
export { dashboardFilterFields } from "./app/components/dashboard/dashboardFilterFields.ts";
export { default as ProjectViewNavPublisher } from "./app/components/project/ProjectViewNavPublisher.tsx";
export {
  CORE_NAV,
  type ProjectShellContext,
} from "./app/components/project/capabilityNav.ts";
export {
  ROUTES_APP,
  ROUTES_FULL_WIDTH,
  ROUTES_WITH_QUEST_LOG,
  SECTION_HREF_ROUTES,
  SECTION_LABEL_KEYS,
} from "./app/components/project/projectViewRoutes.ts";
export { AgentPromptsMenu } from "./app/components/project/prompts/AgentPromptsMenu.tsx";
export { useAgentPrompt } from "./app/components/project/prompts/useAgentPrompt.ts";
export { useAgentPromptSubject } from "./app/components/project/prompts/useAgentPromptSubject.ts";
export {
  type ReportsKpi,
  default as ReportsKpiRow,
} from "./app/components/project/reports/ReportsKpiRow.tsx";
export { default as ReportsSection } from "./app/components/project/reports/ReportsSection.tsx";
export { default as ProjectSettingsCapabilitySection } from "./app/components/project/settings/ProjectSettingsCapabilitySection.tsx";
export { default as AttachmentLightbox } from "./app/components/shared/AttachmentLightbox.tsx";
export { default as CollapsibleBlock } from "./app/components/shared/CollapsibleBlock.tsx";
export { default as CommitLink } from "./app/components/shared/CommitLink.tsx";
export { OutboundLink } from "./app/components/shared/OutboundLink.tsx";
export { ProjectIcon } from "./app/components/shared/ProjectIcon.tsx";
export { default as RedirectPage } from "./app/components/shared/RedirectPage.tsx";
export { default as TokenReveal } from "./app/components/shared/TokenReveal.tsx";
export { default as ToolbarSpinner } from "./app/components/shared/ToolbarSpinner.tsx";
export { attachmentPreview } from "./app/components/shared/attachmentPreview.ts";
export {
  type BulkOutcome,
  settleBulk,
} from "./app/components/shared/bulkOutcome.ts";
export { default as LoreEditor } from "./app/components/shared/element/LoreEditor.tsx";
export { default as LoreViewer } from "./app/components/shared/element/LoreViewer.tsx";
export { default as WikiLinkHoverProvider } from "./app/components/shared/element/WikiLinkHoverProvider.tsx";
export { default as WikiLinkPreviewState } from "./app/components/shared/element/WikiLinkPreviewState.tsx";
export type { ElementRef } from "./app/components/shared/element/elementRef.ts";
export { splitMarkdownCode } from "./app/components/shared/element/markdownCodeSegments.ts";
export { referencedIds } from "./app/components/shared/element/referencedIds.ts";
export { rewriteWikiLinks } from "./app/components/shared/element/rewriteWikiLinks.ts";
export {
  formatReference,
  isReferenceKind,
  parseTypedReference,
} from "./app/components/shared/element/typedReference.ts";
export { useElementLinks } from "./app/components/shared/element/useElementLinks.ts";
export { useKindReferences } from "./app/components/shared/element/useKindReferences.ts";
export { useLoreEditorControl } from "./app/components/shared/element/useLoreEditorControl.ts";
export {
  type AttachmentRef,
  BROKEN_HREF_PREFIX,
  type ElementReference,
  type WikiLinkResolver,
  createWikiLinkResolver,
  formatAttachmentBytes,
} from "./app/components/shared/element/wikiLinkResolver.ts";
export { default as PageHeader } from "./app/components/shared/header/PageHeader.tsx";
export { lazyPart } from "./app/components/shared/lazyPart.tsx";
export {
  default as MarkdownEditor,
  preloadMarkdownEditor,
} from "./app/components/shared/markdown-editor/MarkdownEditor.tsx";
export { default as MarkdownModeToggle } from "./app/components/shared/markdown-editor/MarkdownModeToggle.tsx";
export {
  type MarkdownCommandId,
  markdownCommands,
} from "./app/components/shared/markdown-editor/markdownCommands.ts";
export { matchProjectNav } from "./app/components/shared/spotlight/matchProjectNav.ts";
export { useBulkReport } from "./app/components/shared/useBulkReport.ts";
export {
  type ProjectUser,
  useProjectUsers,
} from "./app/components/shared/useProjectUsers.ts";
export { useRank } from "./app/components/shared/useRank.ts";
export {
  type AgentPromptItemSubject,
  type AgentPromptProjectSubject,
  type AgentPromptSubject,
  renderPromptTemplate,
} from "./app/prompts/renderPromptTemplate.ts";
export { AccountDeletionRegistry } from "./app/registries/AccountDeletionRegistry.ts";
export { AgentPromptRegistry } from "./app/registries/AgentPromptRegistry.ts";
export {
  type DashboardPickerContext,
  DashboardPickerRegistry,
  type DashboardScopeOption,
} from "./app/registries/DashboardPickerRegistry.ts";
export { DocumentSinkRegistry } from "./app/registries/DocumentSinkRegistry.ts";
export {
  ElementReferenceRegistry,
  type ElementReferenceSet,
  type WikiLinkPreviewProps,
} from "./app/registries/ElementReferenceRegistry.ts";
export { ProjectLoaderRegistry } from "./app/registries/ProjectLoaderRegistry.ts";
export {
  type ProjectCreateDialogProps,
  ProjectShellRegistry,
} from "./app/registries/ProjectShellRegistry.ts";
export { ReportsTabRegistry } from "./app/registries/ReportsTabRegistry.ts";
export {
  type LinkedCollection,
  ResourceTabRegistry,
  type ResourceTabSubject,
} from "./app/registries/ResourceTabRegistry.ts";
export { I18n } from "./app/services/I18n.ts";
export { ProjectScopeGrants } from "./app/services/ProjectScopeGrants.ts";
export { capabilityRegistry } from "./app/services/capabilityRegistry.ts";
export { setCurrentProject } from "./app/services/currentProjectWrite.ts";
export { descriptionSnippet } from "./app/services/descriptionSnippet.ts";
export { displayName } from "./app/services/displayName.ts";
export { loreDocsUrl } from "./app/services/docsUrl.ts";
export {
  matchMentions,
  mentionPattern,
  resolveMentionCapture,
} from "./app/services/mentions.ts";
export {
  capabilityOption,
  hasCapability,
} from "./app/services/projectCapabilities.ts";
export { canInProject } from "./app/services/projectRank.ts";

// ---- modules a route or a lazy boundary loads (#E75, #Q2611) ----
//
// A module both statically and dynamically imported is hoisted into the
// static graph, and its page then ships no chunk of its own: the build's
// preload check refuses that. So a lazily loaded page is re-exported here
// only when another package renders it inline, and otherwise as types alone,
// which are erased and add no edge. A spec reaches the rest through
// `@lore/core/testing`, which nothing at runtime imports.
export type { MarkdownEditorMode } from "./app/components/shared/markdown-editor/MarkdownEditorInner.client.tsx";
export { default as LazyProjectActivityPage } from "./app/components/project/activity/LazyProjectActivityPage.tsx";
