import { AccountRouter, accountRouterOptionsAtom } from "@alepha/ui/account";
import { $module } from "alepha";
import { AlephaCrypto } from "alepha/crypto";
import { I18nProvider } from "alepha/react/i18n";
import { AlephaReactUi } from "alepha/react/ui";
import { createElement, lazy, Suspense } from "react";

import { currentProjectAtom } from "./app/atoms/currentProjectAtom.ts";
import { currentProjectMemberAtom } from "./app/atoms/currentProjectMemberAtom.ts";
import { projectPromptsAtom } from "./app/atoms/projectPromptsAtom.ts";
import { userProjectsAtom } from "./app/atoms/userProjectsAtom.ts";
import AccountDeleteWarning from "./app/components/account/AccountDeleteWarning.tsx";
import { LoreAccountRouter } from "./app/components/account/LoreAccountRouter.ts";
import { CoreRouter } from "./app/CoreRouter.ts";
import { I18n } from "./app/services/I18n.ts";
import { ThemesProvider } from "./app/services/ThemesProvider.ts";

/**
 * The browser-safe half of `@lore/core`, the glue: projects, capabilities, ranks and permissions, notifications, audits, the resource registry and its link graph, search, the dashboard, reports, agent prompts and the web shell: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreCoreWeb = $module({
  name: "lore.core.web",
  imports: [AlephaReactUi, AlephaCrypto],
  atoms: [
    currentProjectAtom,
    currentProjectMemberAtom,
    projectPromptsAtom,
    userProjectsAtom,
  ],
  register(alepha) {
    // Injected here rather than listed in `services`: a listed service is
    // tagged with this module, and injecting it anywhere then registers the
    // whole module, router included. This module's barrel is what every
    // component imports from, so a spec rendering one `AccountRouter` page,
    // or reading the dictionaries, would boot Lore's whole page tree.
    alepha.inject(I18n);
    alepha.inject(ThemesProvider);
    alepha.inject(CoreRouter);
    alepha.inject(AccountRouter);
    alepha.inject(LoreAccountRouter);

    // Lore's `quests.createdBy` cascades, so deleting an account also deletes
    // every quest it authored, including inside other people's projects. The
    // framework cannot know that; this fills the dialog's warning slot so the
    // consequences are stated before the click rather than discovered after
    // it, each module's line registered on `AccountDeletionRegistry`.
    //
    // `/account` is a root shell like `/admin` (#E68): not adopted into
    // `CoreRouter.layout`, so its chrome is set here. The brand is Lore's
    // mark linking home, loaded lazily so the account chrome stays out of
    // the bundle every page loads; `Suspense` holds the header empty for the
    // moment the chunk takes.
    alepha.store.set(accountRouterOptionsAtom, {
      brand: createElement(
        Suspense,
        { fallback: null },
        createElement(
          lazy(() => import("./app/components/account/LoreAccountBrand.tsx")),
        ),
      ),
      homeRouteName: "home",
      pages: {
        security: { deleteWarning: createElement(AccountDeleteWarning) },
      },
    });

    // Dogfood locale-prefix routing: French gets `/fr/...` URLs, English (the
    // default) stays unprefixed. Source of truth is the URL, with hreflang
    // alternates emitted for SEO.
    alepha.inject(I18nProvider).options.routing = "prefix";
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { $pageProject, $pageProjectSettings } from "./app/$pageProject.ts";
export { CoreRouter } from "./app/CoreRouter.ts";
export { ProjectRouter } from "./app/ProjectRouter.ts";
export { currentProjectAtom } from "./app/atoms/currentProjectAtom.ts";
export { currentProjectMemberAtom } from "./app/atoms/currentProjectMemberAtom.ts";
export { homeBoardAtom } from "./app/atoms/homeBoardAtom.ts";
export { projectDashboardAtom } from "./app/atoms/projectDashboardAtom.ts";
export {
  type ProjectNavEntry,
  projectNavAtom,
} from "./app/atoms/projectNavAtom.ts";
export { projectPromptsAtom } from "./app/atoms/projectPromptsAtom.ts";
export { realmSettingsAtom } from "./app/atoms/realmSettingsAtom.ts";
export { spotlightOpenAtom } from "./app/atoms/spotlightOpenAtom.ts";
export { userProjectsAtom } from "./app/atoms/userProjectsAtom.ts";
export { default as AccountDeleteWarning } from "./app/components/account/AccountDeleteWarning.tsx";
export { LoreAccountRouter } from "./app/components/account/LoreAccountRouter.ts";
export {
  default as AuthRegisterInvitationNotice,
  type AuthRegisterInvitationNoticeProps,
} from "./app/components/auth/AuthRegisterInvitationNotice.tsx";
export { isOAuthReturnTarget } from "./app/components/auth/oauthReturnTarget.ts";
export {
  type RegisterIntent,
  resolveRegisterIntent,
} from "./app/components/auth/registerIntents.ts";
export {
  default as DashboardCard,
  type DashboardCardProps,
} from "./app/components/dashboard/DashboardCard.tsx";
export {
  default as DashboardCardFooter,
  type DashboardCardFooterProps,
} from "./app/components/dashboard/DashboardCardFooter.tsx";
export {
  default as DashboardCardMenu,
  type DashboardCardMenuProps,
} from "./app/components/dashboard/DashboardCardMenu.tsx";
export {
  default as DashboardCardValue,
  type DashboardCardValueProps,
} from "./app/components/dashboard/DashboardCardValue.tsx";
export {
  default as DashboardCatalogue,
  type DashboardCatalogueProps,
} from "./app/components/dashboard/DashboardCatalogue.tsx";
export {
  default as DashboardCatalogueRow,
  type DashboardCatalogueRowProps,
} from "./app/components/dashboard/DashboardCatalogueRow.tsx";
export {
  default as DashboardFilterStep,
  type DashboardFilterStepProps,
} from "./app/components/dashboard/DashboardFilterStep.tsx";
export {
  default as DashboardGrid,
  type DashboardGridProps,
} from "./app/components/dashboard/DashboardGrid.tsx";
export {
  type DashboardScopeApp,
  type DashboardScopeProject,
  default as DashboardScopeStep,
  type DashboardScopeStepProps,
} from "./app/components/dashboard/DashboardScopeStep.tsx";
export {
  DASHBOARD_NO_VALUE,
  dashboardFilterChipKeys,
  dashboardFilterChipLabels,
} from "./app/components/dashboard/dashboardChips.ts";
export {
  type DashboardEligibleProject,
  eligibleApps,
  eligibleProjects,
  metricUnavailableKey,
  projectAnswers,
} from "./app/components/dashboard/dashboardEligibility.ts";
export {
  type DashboardFilterField,
  dashboardFilterFields,
} from "./app/components/dashboard/dashboardFilterFields.ts";
export { dashboardMetricIcon } from "./app/components/dashboard/dashboardMetricIcon.ts";
export { default as HomeBoard } from "./app/components/home/HomeBoard.tsx";
export { default as HomeHeader } from "./app/components/home/HomeHeader.tsx";
export {
  HomeMomentum,
  type HomeMomentumProps,
} from "./app/components/home/HomeMomentum.tsx";
export {
  type HomeOpenLink,
  HomeOpenLinks,
  type HomeOpenLinksProps,
} from "./app/components/home/HomeOpenLinks.tsx";
export {
  HomeRecentProjectRow,
  type HomeRecentProjectRowProps,
} from "./app/components/home/HomeRecentProjectRow.tsx";
export {
  HomeRecentProjects,
  type HomeRecentProjectsProps,
} from "./app/components/home/HomeRecentProjects.tsx";
export {
  HomeSearch,
  type HomeSearchProps,
} from "./app/components/home/HomeSearch.tsx";
export {
  HomeSearchRow,
  type HomeSearchRowItem,
  type HomeSearchRowProps,
} from "./app/components/home/HomeSearchRow.tsx";
export {
  HOME_INACTIVE_AFTER_DAYS,
  activityAgeInDays,
} from "./app/components/home/homeActivityAge.ts";
export {
  EMPTY_BAR,
  MIN_BAR,
  momentumBarHeights,
  momentumDelta,
} from "./app/components/home/homeMomentumBars.ts";
export { useHomeOpenTags } from "./app/components/home/useHomeOpenTags.ts";
export {
  type HomeSearchGroup,
  type HomeSearchHit,
  useHomeSearch,
} from "./app/components/home/useHomeSearch.ts";
export { useHomeSearchHitHref } from "./app/components/home/useHomeSearchHitHref.ts";
export { default as ProjectActionsCreateButton } from "./app/components/project/ProjectActionsCreateButton.tsx";
export { default as ProjectCreateBackdrop } from "./app/components/project/ProjectCreateBackdrop.tsx";
export { default as ProjectInboxButton } from "./app/components/project/ProjectInboxButton.tsx";
export { default as ProjectSwitcher } from "./app/components/project/ProjectSwitcher.tsx";
export {
  default as ProjectUpdate,
  type ProjectUpdateProps,
} from "./app/components/project/ProjectUpdate.tsx";
export {
  default as ProjectViewNavPublisher,
  type ProjectViewNavPublisherProps,
} from "./app/components/project/ProjectViewNavPublisher.tsx";
export {
  ActivityDetails,
  type ActivityDetailsProps,
} from "./app/components/project/activity/ActivityDetails.tsx";
export { activityResourceHref } from "./app/components/project/activity/activityResourceHref.ts";
export { activityResourceIcon } from "./app/components/project/activity/activityResourceIcon.ts";
export {
  activityResourceLabel,
  capitalize,
} from "./app/components/project/activity/activityResourceLabel.ts";
export {
  CORE_NAV,
  type CapabilityNavEntry,
  type ProjectShellContext,
} from "./app/components/project/capabilityNav.ts";
export {
  default as ProjectDashboardEmpty,
  type ProjectDashboardEmptyProps,
} from "./app/components/project/dashboard/ProjectDashboardEmpty.tsx";
export {
  default as ProjectDashboardHeader,
  type ProjectDashboardHeaderProps,
} from "./app/components/project/dashboard/ProjectDashboardHeader.tsx";
export {
  ROUTES_APP,
  ROUTES_FULL_WIDTH,
  ROUTES_WITH_QUEST_LOG,
  SECTION_HREF_ROUTES,
  SECTION_LABEL_KEYS,
} from "./app/components/project/projectViewRoutes.ts";
export {
  AgentPromptsMenu,
  type AgentPromptsMenuItem,
  type AgentPromptsMenuProps,
} from "./app/components/project/prompts/AgentPromptsMenu.tsx";
export {
  type AgentPromptHandle,
  useAgentPrompt,
} from "./app/components/project/prompts/useAgentPrompt.ts";
export {
  type AgentPromptItem,
  useAgentPromptSubject,
} from "./app/components/project/prompts/useAgentPromptSubject.ts";
export { RECENT_PROJECTS_CAP } from "./app/components/project/recentProjectsCap.ts";
export {
  type ReportsKpi,
  default as ReportsKpiRow,
  type ReportsKpiRowProps,
} from "./app/components/project/reports/ReportsKpiRow.tsx";
export {
  default as ReportsSection,
  type ReportsSectionProps,
} from "./app/components/project/reports/ReportsSection.tsx";
export {
  ProjectSettingsAgentPromptEditor,
  type ProjectSettingsAgentPromptEditorProps,
} from "./app/components/project/settings/ProjectSettingsAgentPromptEditor.tsx";
export {
  default as ProjectSettingsCapabilitySection,
  type ProjectSettingsCapabilitySectionProps,
} from "./app/components/project/settings/ProjectSettingsCapabilitySection.tsx";
export {
  default as ProjectSettingsConfirmationModal,
  type ProjectSettingsConfirmationModalProps,
} from "./app/components/project/settings/ProjectSettingsConfirmationModal.tsx";
export { default as ProjectSettingsDangerZoneSection } from "./app/components/project/settings/ProjectSettingsDangerZoneSection.tsx";
export {
  CORE_SETTINGS_SECTIONS,
  type SettingsSectionDef,
  type SettingsTab,
  visibleSettingsTabs,
} from "./app/components/project/settings/projectSettingsSections.ts";
export {
  type CapabilitySwitch,
  useCapabilityOption,
  useCapabilityToggle,
} from "./app/components/project/settings/useCapability.ts";
export {
  default as AttachmentLightbox,
  type AttachmentLightboxProps,
  type PreviewableAttachment,
} from "./app/components/shared/AttachmentLightbox.tsx";
export {
  default as CollapsibleBlock,
  type CollapsibleBlockProps,
} from "./app/components/shared/CollapsibleBlock.tsx";
export {
  default as CommitLink,
  type CommitLinkProps,
} from "./app/components/shared/CommitLink.tsx";
export { default as ErrorPage } from "./app/components/shared/ErrorPage.tsx";
export {
  default as LoreLogo,
  type LoreLogoProps,
} from "./app/components/shared/LoreLogo.tsx";
export {
  MemberIdentity,
  type MemberIdentityProps,
  type MemberWithUser,
} from "./app/components/shared/MemberIdentity.tsx";
export {
  OutboundLink,
  type OutboundLinkProps,
} from "./app/components/shared/OutboundLink.tsx";
export {
  ProjectIcon,
  type ProjectIconProps,
} from "./app/components/shared/ProjectIcon.tsx";
export { default as RedirectPage } from "./app/components/shared/RedirectPage.tsx";
export {
  default as TokenReveal,
  type TokenRevealProps,
} from "./app/components/shared/TokenReveal.tsx";
export {
  default as ToolbarSpinner,
  type ToolbarSpinnerProps,
} from "./app/components/shared/ToolbarSpinner.tsx";
export {
  type AttachmentPreview,
  PREVIEW_MAX_BYTES,
  attachmentPreview,
} from "./app/components/shared/attachmentPreview.ts";
export {
  type BulkOutcome,
  settleBulk,
} from "./app/components/shared/bulkOutcome.ts";
export {
  default as LoreEditor,
  type LoreEditorProps,
} from "./app/components/shared/element/LoreEditor.tsx";
export {
  default as LoreViewer,
  type LoreViewerProps,
} from "./app/components/shared/element/LoreViewer.tsx";
export {
  type BrokenReason,
  default as WikiLinkHoverProvider,
  type WikiLinkHoverProviderProps,
} from "./app/components/shared/element/WikiLinkHoverProvider.tsx";
export {
  default as WikiLinkPreviewState,
  type WikiLinkPreviewStateProps,
} from "./app/components/shared/element/WikiLinkPreviewState.tsx";
export type { ElementRef } from "./app/components/shared/element/elementRef.ts";
export {
  type MarkdownSegment,
  outsideMarkdownCode,
  splitMarkdownCode,
} from "./app/components/shared/element/markdownCodeSegments.ts";
export { referencedIds } from "./app/components/shared/element/referencedIds.ts";
export { rewriteWikiLinks } from "./app/components/shared/element/rewriteWikiLinks.ts";
export {
  REFERENCE_LETTERS,
  type ReferenceKind,
  type TypedReference,
  formatReference,
  isReferenceKind,
  parseTypedReference,
} from "./app/components/shared/element/typedReference.ts";
export { useElementImageUpload } from "./app/components/shared/element/useElementImageUpload.ts";
export {
  type ElementLinks,
  useElementLinks,
} from "./app/components/shared/element/useElementLinks.ts";
export {
  type HoverCardPosition,
  useHoverCardPosition,
} from "./app/components/shared/element/useHoverCardPosition.ts";
export {
  type KindReferences,
  useKindReferences,
} from "./app/components/shared/element/useKindReferences.ts";
export { useLoreEditorControl } from "./app/components/shared/element/useLoreEditorControl.ts";
export {
  type AttachmentRef,
  BROKEN_HREF_PREFIX,
  type BrokenWikiLinkReason,
  type ElementReference,
  type ElementReferenceLinks,
  type WikiLinkResolver,
  type WikiLinkResolverInput,
  type WikiLinkTarget,
  createWikiLinkResolver,
  formatAttachmentBytes,
  isImageAttachment,
} from "./app/components/shared/element/wikiLinkResolver.ts";
export type { WikiLinkSuggestion } from "./app/components/shared/element/wikiLinkSuggestion.ts";
export {
  default as HeaderActions,
  type HeaderActionsProps,
} from "./app/components/shared/header/HeaderActions.tsx";
export { default as HeaderRepositoryButton } from "./app/components/shared/header/HeaderRepositoryButton.tsx";
export { default as HeaderSearchButton } from "./app/components/shared/header/HeaderSearchButton.tsx";
export {
  default as PageHeader,
  type PageHeaderProps,
} from "./app/components/shared/header/PageHeader.tsx";
export { lazyPart } from "./app/components/shared/lazyPart.tsx";
export {
  default as CodeMirrorEditor,
  type CodeMirrorEditorProps,
} from "./app/components/shared/markdown-editor/CodeMirrorEditor.tsx";
export {
  default as MarkdownEditor,
  type MarkdownEditorProps,
  preloadMarkdownEditor,
} from "./app/components/shared/markdown-editor/MarkdownEditor.tsx";
export {
  default as MarkdownFormatToolbar,
  type MarkdownFormatToolbarProps,
} from "./app/components/shared/markdown-editor/MarkdownFormatToolbar.tsx";
export {
  default as MarkdownModeToggle,
  type MarkdownModeToggleProps,
} from "./app/components/shared/markdown-editor/MarkdownModeToggle.tsx";
export {
  default as MarkdownSelectionToolbar,
  type MarkdownSelectionToolbarProps,
} from "./app/components/shared/markdown-editor/MarkdownSelectionToolbar.tsx";
export {
  default as MarkdownToolbarBand,
  type MarkdownToolbarBandProps,
} from "./app/components/shared/markdown-editor/MarkdownToolbarBand.tsx";
export {
  type MarkdownExtensionOptions,
  createMarkdownExtensions,
} from "./app/components/shared/markdown-editor/codeMirrorSetup.ts";
export { fenceBlockHighlight } from "./app/components/shared/markdown-editor/fenceDecorations.ts";
export {
  buildInsertion,
  imageMarkdown,
  insertAtCursor,
} from "./app/components/shared/markdown-editor/insertAtCursor.ts";
export {
  type MarkdownCommandId,
  markdownCommands,
} from "./app/components/shared/markdown-editor/markdownCommands.ts";
export {
  MARKDOWN_TOOLBAR_GROUPS,
  type MarkdownToolbarAction,
} from "./app/components/shared/markdown-editor/markdownToolbarActions.ts";
export {
  DIAGRAM_BLOCK,
  TABLE_BLOCK,
  insertBlock,
  toggleFencedCode,
  toggleInlineMarker,
  toggleLinePrefix,
  wrapAsLink,
} from "./app/components/shared/markdown-editor/markdownTransforms.ts";
export { createMentionCompletion } from "./app/components/shared/markdown-editor/mentionCompletion.ts";
export {
  type SyncCompletionSource,
  createWikiLinkCompletion,
} from "./app/components/shared/markdown-editor/wikiLinkCompletion.ts";
export { default as Spotlight } from "./app/components/shared/spotlight/Spotlight.tsx";
export { matchProjectNav } from "./app/components/shared/spotlight/matchProjectNav.ts";
export { useAtomsVersion } from "./app/components/shared/useAtomsVersion.ts";
export {
  type BulkReport,
  useBulkReport,
} from "./app/components/shared/useBulkReport.ts";
export {
  type ProjectRanks,
  useProjectRanks,
} from "./app/components/shared/useProjectRanks.ts";
export {
  type ProjectUser,
  useProjectUsers,
} from "./app/components/shared/useProjectUsers.ts";
export { type Rank, useRank } from "./app/components/shared/useRank.ts";
export {
  type AgentPromptItemSubject,
  type AgentPromptProjectSubject,
  type AgentPromptSubject,
  renderPromptTemplate,
} from "./app/prompts/renderPromptTemplate.ts";
export {
  AccountDeletionRegistry,
  type AccountDeletionWarning,
} from "./app/registries/AccountDeletionRegistry.ts";
export {
  type AgentPromptKindEntry,
  AgentPromptRegistry,
} from "./app/registries/AgentPromptRegistry.ts";
export {
  type DashboardAppSource,
  type DashboardPickerContext,
  DashboardPickerRegistry,
  type DashboardScopeOption,
  type DashboardSubjectOptions,
  type DashboardSubjectPicker,
  type DashboardTagSource,
} from "./app/registries/DashboardPickerRegistry.ts";
export {
  type DocumentSink,
  DocumentSinkRegistry,
  type SavedDocument,
} from "./app/registries/DocumentSinkRegistry.ts";
export {
  type ElementReferenceKind,
  ElementReferenceRegistry,
  type ElementReferenceSet,
  type WikiLinkPreviewProps,
} from "./app/registries/ElementReferenceRegistry.ts";
export {
  type ProjectLoaderContribution,
  ProjectLoaderRegistry,
} from "./app/registries/ProjectLoaderRegistry.ts";
export {
  type ProjectAsideContribution,
  type ProjectCreateDialogProps,
  type ProjectCreateItem,
  type ProjectCrumbContribution,
  type ProjectLinkContext,
  type ProjectPaletteContribution,
  type ProjectSettingsPanel,
  ProjectShellRegistry,
  type ShellProject,
} from "./app/registries/ProjectShellRegistry.ts";
export {
  type ReportsTab,
  ReportsTabRegistry,
} from "./app/registries/ReportsTabRegistry.ts";
export {
  type LinkedCollection,
  type ResourceTab,
  ResourceTabRegistry,
  type ResourceTabSubject,
} from "./app/registries/ResourceTabRegistry.ts";
export { I18n } from "./app/services/I18n.ts";
export { ProjectScopeGrants } from "./app/services/ProjectScopeGrants.ts";
export { ThemesProvider } from "./app/services/ThemesProvider.ts";
export { capabilityRegistry } from "./app/services/capabilityRegistry.ts";
export { setCurrentProject } from "./app/services/currentProjectWrite.ts";
export { descriptionSnippet } from "./app/services/descriptionSnippet.ts";
export { displayName } from "./app/services/displayName.ts";
export { loreDocsUrl } from "./app/services/docsUrl.ts";
export { publicFileUrl } from "./app/services/fileUrl.ts";
export {
  matchMentions,
  mentionPattern,
  resolveMentionCapture,
} from "./app/services/mentions.ts";
export {
  capabilityOption,
  hasCapability,
} from "./app/services/projectCapabilities.ts";
export {
  type ProjectRankSource,
  canInProject,
} from "./app/services/projectRank.ts";

// ---- modules a route or a lazy boundary loads (#E75, #Q2611) ----
//
// A module both statically and dynamically imported is hoisted into the
// static graph, and its page then ships no chunk of its own: the build's
// preload check refuses that. So a lazily loaded page is re-exported here
// only when another package renders it inline, and otherwise as types alone,
// which are erased and add no edge. A spec reaches the rest through
// `@lore/core/testing`, which nothing at runtime imports.
export type {
  MarkdownEditorInnerProps,
  MarkdownEditorMode,
} from "./app/components/shared/markdown-editor/MarkdownEditorInner.client.tsx";
export type { ProjectActivityPageProps } from "./app/components/project/activity/ProjectActivityPage.tsx";
export { default as LazyProjectActivityPage } from "./app/components/project/activity/LazyProjectActivityPage.tsx";
