import { LoreCoreWeb } from "@lore/core/web";
import { $module } from "alepha";

import { WorkDashboardMetrics } from "../api/services/WorkDashboardMetrics.ts";
import { currentAssignedQuestsAtom } from "./app/atoms/currentAssignedQuestsAtom.ts";
import { currentEpicsAtom } from "./app/atoms/currentEpicsAtom.ts";
import { currentQuestAtom } from "./app/atoms/currentQuestAtom.ts";
import { currentReleasesAtom } from "./app/atoms/currentReleasesAtom.ts";
import { kanbanFiltersAtom } from "./app/atoms/kanbanFiltersAtom.ts";
import { kanbanReloadAtom } from "./app/atoms/kanbanReloadAtom.ts";
import { questLogCollapsedAtom } from "./app/atoms/questLogCollapsedAtom.ts";
import { WorkAccountRouter } from "./app/components/account/feedback/WorkAccountRouter.ts";
import { WorkProjectLoader } from "./app/loaders/WorkProjectLoader.ts";
import { WorkShell } from "./app/shell/WorkShell.ts";
import { WorkRouter } from "./app/WorkRouter.ts";

/**
 * The browser-safe half of `@lore/work`, Lore as Jira: quests, epics, releases, areas, the kanban, the roadmap and feedback: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreWorkWeb = $module({
  name: "lore.work.web",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreWeb],
  atoms: [
    currentAssignedQuestsAtom,
    currentReleasesAtom,
    currentEpicsAtom,
    currentQuestAtom,
    kanbanFiltersAtom,
    kanbanReloadAtom,
    // Registered here, unlike most of the `current*` atoms, so the cookie
    // value is hydrated before the first render that reads it. An
    // unregistered `persist: "cookie"` atom still persists, lazily, on its
    // first read.
    questLogCollapsedAtom,
  ],
  register(alepha) {
    // Injected rather than listed in `services`: a listed service is tagged
    // with this module, and injecting it anywhere (a spec, a component
    // importing it from the barrel) would then register the whole module.
    //
    // The pages; Work's account page; its part of opening a project and of
    // the project shell (sidebar, settings, create menu, breadcrumbs,
    // references, tabs, prompts, pickers), on core's registries, which
    // nothing else would construct; and its dashboard metrics' declarative
    // half, which the browser needs to draw the tiles.
    alepha.inject(WorkRouter);
    alepha.inject(WorkAccountRouter);
    alepha.inject(WorkProjectLoader);
    alepha.inject(WorkShell);
    alepha.inject(WorkDashboardMetrics);
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { WorkRouter } from "./app/WorkRouter.ts";
export { currentAreasAtom } from "./app/atoms/currentAreasAtom.ts";
export { currentAssignedQuestsAtom } from "./app/atoms/currentAssignedQuestsAtom.ts";
export { currentEpicAtom } from "./app/atoms/currentEpicAtom.ts";
export { currentEpicCountAtom } from "./app/atoms/currentEpicCountAtom.ts";
export { currentEpicsAtom } from "./app/atoms/currentEpicsAtom.ts";
export { currentFeedbackCountAtom } from "./app/atoms/currentFeedbackCountAtom.ts";
export { currentQuestAtom } from "./app/atoms/currentQuestAtom.ts";
export { currentQuestCountAtom } from "./app/atoms/currentQuestCountAtom.ts";
export { currentReleasesAtom } from "./app/atoms/currentReleasesAtom.ts";
export { kanbanFiltersAtom } from "./app/atoms/kanbanFiltersAtom.ts";
export { kanbanReloadAtom } from "./app/atoms/kanbanReloadAtom.ts";
export { questLogCollapsedAtom } from "./app/atoms/questLogCollapsedAtom.ts";
export { roadmapNotFoundAtom } from "./app/atoms/roadmapNotFoundAtom.ts";
export {
  default as MyFeedbackEditSheet,
  type MyFeedbackEditSheetProps,
} from "./app/components/account/feedback/MyFeedbackEditSheet.tsx";
export { WorkAccountRouter } from "./app/components/account/feedback/WorkAccountRouter.ts";
export {
  default as KanbanBoard,
  type KanbanBoardProps,
} from "./app/components/kanban/KanbanBoard.tsx";
export {
  default as KanbanCard,
  type KanbanCardProps,
} from "./app/components/kanban/KanbanCard.tsx";
export {
  type ColumnDescriptor,
  type ColumnKind,
  default as KanbanColumn,
  type KanbanColumnProps,
} from "./app/components/kanban/KanbanColumn.tsx";
export {
  default as KanbanColumnComposer,
  type KanbanColumnComposerProps,
} from "./app/components/kanban/KanbanColumnComposer.tsx";
export {
  default as KanbanColumnMenu,
  type KanbanColumnMenuProps,
} from "./app/components/kanban/KanbanColumnMenu.tsx";
export {
  type AgingLevel,
  KanbanAging,
} from "./app/components/kanban/kanbanAging.ts";
export { KanbanGrouping } from "./app/components/kanban/kanbanGrouping.ts";
export {
  type KanbanLane,
  KanbanLanes,
  type LaneMode,
  UNGROUPED,
} from "./app/components/kanban/kanbanLanes.ts";
export {
  type KanbanColumnOps,
  useKanbanColumnOps,
} from "./app/components/kanban/useKanbanColumnOps.ts";
export {
  type KanbanMoveInput,
  useKanbanMove,
} from "./app/components/kanban/useKanbanMove.ts";
export type { ProjectKanbanCardProps } from "./app/components/project/ProjectKanbanCard.tsx";
export {
  default as ProjectQuestLogRail,
  type ProjectQuestLogRailProps,
} from "./app/components/project/ProjectQuestLogRail.tsx";
export { default as ProjectQuestsTable } from "./app/components/project/ProjectQuestsTable.tsx";
export {
  default as QuestLog,
  type QuestLogProps,
} from "./app/components/project/QuestLog.tsx";
export {
  default as EpicCreate,
  type EpicCreateProps,
} from "./app/components/project/epics/EpicCreate.tsx";
export {
  default as EpicCreateSheet,
  type EpicCreateSheetProps,
} from "./app/components/project/epics/EpicCreateSheet.tsx";
export {
  default as EpicQuestPicker,
  type EpicQuestPickerProps,
} from "./app/components/project/epics/EpicQuestPicker.tsx";
export {
  default as EpicReleaseControl,
  type EpicReleaseControlProps,
} from "./app/components/project/epics/EpicReleaseControl.tsx";
export {
  default as EpicStatusControl,
  type EpicStatusControlProps,
} from "./app/components/project/epics/EpicStatusControl.tsx";
export type { ProjectEpicProps } from "./app/components/project/epics/ProjectEpic.tsx";
export {
  default as ProjectEpicAside,
  type ProjectEpicAsideProps,
} from "./app/components/project/epics/ProjectEpicAside.tsx";
export {
  default as ProjectEpicDescription,
  type ProjectEpicDescriptionProps,
} from "./app/components/project/epics/ProjectEpicDescription.tsx";
export {
  default as ProjectEpicFlow,
  type ProjectEpicFlowProps,
} from "./app/components/project/epics/ProjectEpicFlow.tsx";
export {
  default as ProjectEpicQuests,
  type ProjectEpicQuestsProps,
} from "./app/components/project/epics/ProjectEpicQuests.tsx";
export {
  default as ProjectEpicsProgress,
  type ProjectEpicsProgressProps,
} from "./app/components/project/epics/ProjectEpicsProgress.tsx";
export {
  type EpicStatus,
  type EpicStatusLabelKey,
  STATUS_ICONS,
  STATUS_LABEL_KEYS,
  STATUS_ORDER,
  STATUS_TONE,
  epicBlockedBy,
} from "./app/components/project/epics/epicStatus.ts";
export { useDashboardEpicOptions } from "./app/components/project/epics/useDashboardEpicOptions.ts";
export { useEpicReferences } from "./app/components/project/epics/useEpicReferences.ts";
export {
  default as FeedbackThread,
  type FeedbackThreadProps,
} from "./app/components/project/feedback/FeedbackThread.tsx";
export {
  default as FeedbackThreadBody,
  type FeedbackThreadBodyProps,
} from "./app/components/project/feedback/FeedbackThreadBody.tsx";
export type { ProjectFeedbackProps } from "./app/components/project/feedback/ProjectFeedback.tsx";
export {
  default as ProjectFeedbackCard,
  type ProjectFeedbackCardProps,
} from "./app/components/project/feedback/ProjectFeedbackCard.tsx";
export {
  default as ProjectFeedbackDetail,
  type ProjectFeedbackDetailProps,
} from "./app/components/project/feedback/ProjectFeedbackDetail.tsx";
export {
  default as ProjectFeedbackEmptyState,
  type ProjectFeedbackEmptyStateProps,
} from "./app/components/project/feedback/ProjectFeedbackEmptyState.tsx";
export { FEEDBACK_PAGE_SIZE } from "./app/components/project/feedback/feedbackPageSize.ts";
export { useFeedbackReferences } from "./app/components/project/feedback/useFeedbackReferences.ts";
export {
  type QuestAgentGateReason,
  questAgentGate,
} from "./app/components/project/prompts/questAgentGate.ts";
export { useWorkPromptSubject } from "./app/components/project/prompts/useWorkPromptSubject.ts";
export {
  default as LazyQuestView,
  preloadQuestView,
} from "./app/components/project/quest/LazyQuestView.tsx";
export {
  default as QuestAssigneePicker,
  type QuestAssigneePickerProps,
} from "./app/components/project/quest/QuestAssigneePicker.tsx";
export {
  default as QuestAttachmentChip,
  type QuestAttachmentChipProps,
} from "./app/components/project/quest/QuestAttachmentChip.tsx";
export {
  default as QuestAttachments,
  type QuestAttachmentsProps,
} from "./app/components/project/quest/QuestAttachments.tsx";
export {
  default as QuestCompletionDialog,
  type QuestCompletionDialogProps,
} from "./app/components/project/quest/QuestCompletionDialog.tsx";
export {
  default as QuestCreate,
  type QuestCreateProps,
} from "./app/components/project/quest/QuestCreate.tsx";
export {
  type Objective,
  default as QuestCreateObjectives,
  type QuestCreateObjectivesProps,
} from "./app/components/project/quest/QuestCreateObjectives.tsx";
export {
  default as QuestDependencyPicker,
  type QuestDependencyPickerProps,
} from "./app/components/project/quest/QuestDependencyPicker.tsx";
export {
  default as QuestDescription,
  type QuestDescriptionProps,
} from "./app/components/project/quest/QuestDescription.tsx";
export {
  default as QuestDiscussion,
  type QuestDiscussionProps,
} from "./app/components/project/quest/QuestDiscussion.tsx";
export {
  default as QuestDiscussionComment,
  type QuestDiscussionCommentProps,
} from "./app/components/project/quest/QuestDiscussionComment.tsx";
export {
  default as QuestDiscussionComposer,
  type QuestDiscussionComposerProps,
} from "./app/components/project/quest/QuestDiscussionComposer.tsx";
export {
  default as QuestDiscussionEvent,
  type QuestDiscussionEventProps,
} from "./app/components/project/quest/QuestDiscussionEvent.tsx";
export {
  default as QuestEstimateInput,
  type QuestEstimateInputProps,
} from "./app/components/project/quest/QuestEstimateInput.tsx";
export {
  default as QuestGroup,
  type QuestGroupProps,
} from "./app/components/project/quest/QuestGroup.tsx";
export {
  default as QuestItem,
  type QuestItemProps,
} from "./app/components/project/quest/QuestItem.tsx";
export {
  default as QuestList,
  type QuestListProps,
} from "./app/components/project/quest/QuestList.tsx";
export type { QuestQuestlineProps } from "./app/components/project/quest/QuestQuestline.tsx";
export {
  default as QuestReleaseControl,
  type QuestReleaseControlProps,
} from "./app/components/project/quest/QuestReleaseControl.tsx";
export {
  default as QuestTagInput,
  type QuestTagInputProps,
} from "./app/components/project/quest/QuestTagInput.tsx";
export type {
  QuestViewContext,
  QuestViewProps,
} from "./app/components/project/quest/QuestView.tsx";
export {
  default as QuestViewDuplicateButton,
  type QuestViewDuplicateButtonProps,
} from "./app/components/project/quest/QuestViewDuplicateButton.tsx";
export {
  default as QuestViewEditButton,
  type QuestViewEditButtonProps,
} from "./app/components/project/quest/QuestViewEditButton.tsx";
export {
  default as QuestViewFeedbackBadge,
  type QuestViewFeedbackBadgeProps,
} from "./app/components/project/quest/QuestViewFeedbackBadge.tsx";
export {
  default as QuestViewObjectives,
  type QuestViewObjectivesProps,
} from "./app/components/project/quest/QuestViewObjectives.tsx";
export {
  default as QuestViewQuestline,
  type QuestViewQuestlineProps,
  type QuestlineNode,
  type QuestlineSummary,
} from "./app/components/project/quest/QuestViewQuestline.tsx";
export {
  default as QuestViewRail,
  type QuestViewRailProps,
} from "./app/components/project/quest/QuestViewRail.tsx";
export {
  default as QuestViewRailEpicLink,
  type QuestViewRailEpicLinkProps,
} from "./app/components/project/quest/QuestViewRailEpicLink.tsx";
export {
  default as QuestViewRailRow,
  type QuestViewRailRowProps,
} from "./app/components/project/quest/QuestViewRailRow.tsx";
export {
  default as QuestViewRailTags,
  type QuestViewRailTagsProps,
} from "./app/components/project/quest/QuestViewRailTags.tsx";
export {
  default as QuestViewSettings,
  type QuestViewSettingsProps,
} from "./app/components/project/quest/QuestViewSettings.tsx";
export {
  default as QuestViewTimer,
  type QuestViewTimerProps,
} from "./app/components/project/quest/QuestViewTimer.tsx";
export {
  type CommentReferenceOptions,
  expandCommentReferences,
  outsideProtected,
  protectedSegments,
} from "./app/components/project/quest/commentReferences.ts";
export {
  QUEST_PRIORITY_ICONS,
  QUEST_PRIORITY_RANK,
  QUEST_PRIORITY_TONE,
  QUEST_STATUS_LABEL_KEYS,
  QUEST_STATUS_TONE,
  type QuestStatusLabelKey,
  type QuestTone,
} from "./app/components/project/quest/questChips.ts";
export {
  type QuestDiscussionEntry,
  type QuestEventAction,
  buildQuestDiscussionEntries,
} from "./app/components/project/quest/questDiscussionEntries.ts";
export {
  QuestDueDate,
  type QuestDueState,
} from "./app/components/project/quest/questDueDate.ts";
export {
  ESTIMATE_PRESETS,
  ESTIMATE_UNITS,
  type EstimateUnit,
  formatEstimate,
  splitEstimate,
} from "./app/components/project/quest/questEstimate.ts";
export {
  DEFAULT_QUEST_SIZE,
  QUEST_SIZE_OPTIONS,
  formatQuestSize,
} from "./app/components/project/quest/questSize.ts";
export {
  default as Questline,
  type QuestlineProps,
} from "./app/components/project/quest/questline/Questline.tsx";
export {
  default as QuestlineCard,
  type QuestlineCardProps,
} from "./app/components/project/quest/questline/QuestlineCard.tsx";
export {
  default as QuestlineDialog,
  type QuestlineDialogProps,
} from "./app/components/project/quest/questline/QuestlineDialog.tsx";
export {
  default as QuestlineStatBar,
  type QuestlineStatBarProps,
  type QuestlineStatBarZoom,
} from "./app/components/project/quest/questline/QuestlineStatBar.tsx";
export {
  default as QuestlineTrack,
  type QuestlineTrackProps,
} from "./app/components/project/quest/questline/QuestlineTrack.tsx";
export {
  CARD_H,
  CARD_W,
  COL_GAP,
  type QuestlineItem,
  QuestlineLayout,
  type QuestlineState,
  type QuestlineStatusOf,
  ROW_GAP,
} from "./app/components/project/quest/questline/questlineLayout.ts";
export {
  DRAG_THRESHOLD,
  FIT_PADDING,
  MAX_SCALE,
  MIN_SCALE,
  QuestlineViewport,
  type ViewportRect,
  type ViewportSize,
  type ViewportTransform,
  ZOOM_STEP,
} from "./app/components/project/quest/questline/questlineViewport.ts";
export {
  type QuestlineViewportControls,
  useQuestlineViewport,
} from "./app/components/project/quest/questline/useQuestlineViewport.ts";
export { useAuthoredQuestsDeletionLine } from "./app/components/project/quest/useAuthoredQuestsDeletionLine.ts";
export { useDashboardQuestTags } from "./app/components/project/quest/useDashboardQuestTags.ts";
export { useExclusiveWindowPaste } from "./app/components/project/quest/useExclusiveWindowPaste.ts";
export { useFeedbackReference } from "./app/components/project/quest/useFeedbackReference.ts";
export { useQuestElementImageUpload } from "./app/components/project/quest/useQuestElementImageUpload.ts";
export { useQuestReferences } from "./app/components/project/quest/useQuestReferences.ts";
export { releaseRowMenu } from "./app/components/project/releaseRowMenu.ts";
export {
  default as ReleaseChangelogPanel,
  type ReleaseChangelogPanelProps,
} from "./app/components/project/releases/ReleaseChangelogPanel.tsx";
export {
  default as ReleaseChangelogRow,
  type ReleaseChangelogRowProps,
} from "./app/components/project/releases/ReleaseChangelogRow.tsx";
export {
  default as ReleaseContents,
  type ReleaseContentsData,
  type ReleaseContentsEpic,
  type ReleaseContentsProps,
} from "./app/components/project/releases/ReleaseContents.tsx";
export {
  default as ReleaseCreateDialog,
  type ReleaseCreateDialogProps,
} from "./app/components/project/releases/ReleaseCreateDialog.tsx";
export {
  default as ReleaseDefaultBadge,
  type ReleaseDefaultBadgeProps,
} from "./app/components/project/releases/ReleaseDefaultBadge.tsx";
export {
  default as ReleaseDescriptionEditor,
  type ReleaseDescriptionEditorProps,
} from "./app/components/project/releases/ReleaseDescriptionEditor.tsx";
export {
  default as ReleaseEditForm,
  type ReleaseEditFormProps,
} from "./app/components/project/releases/ReleaseEditForm.tsx";
export {
  default as ReleaseEditSheet,
  type ReleaseEditSheetProps,
} from "./app/components/project/releases/ReleaseEditSheet.tsx";
export {
  default as ReleaseFlow,
  type ReleaseFlowProps,
} from "./app/components/project/releases/ReleaseFlow.tsx";
export {
  default as ReleaseFlowCluster,
  type ReleaseFlowClusterProps,
} from "./app/components/project/releases/ReleaseFlowCluster.tsx";
export {
  default as ReleaseOverviewTab,
  type ReleaseOverviewTabProps,
} from "./app/components/project/releases/ReleaseOverviewTab.tsx";
export {
  default as ReleasePlate,
  type ReleasePlateProps,
} from "./app/components/project/releases/ReleasePlate.tsx";
export {
  type ReleasePriority,
  default as ReleasePriorityPill,
  type ReleasePriorityPillProps,
} from "./app/components/project/releases/ReleasePriorityPill.tsx";
export {
  default as ReleaseProgress,
  type ReleaseProgressProps,
} from "./app/components/project/releases/ReleaseProgress.tsx";
export {
  default as ReleaseProgressBar,
  type ReleaseProgressBarProps,
} from "./app/components/project/releases/ReleaseProgressBar.tsx";
export {
  default as ReleaseQuestRow,
  type ReleaseQuestRowProps,
} from "./app/components/project/releases/ReleaseQuestRow.tsx";
export {
  default as ReleaseSaveToFolioDialog,
  type ReleaseSaveToFolioDialogProps,
} from "./app/components/project/releases/ReleaseSaveToFolioDialog.tsx";
export {
  default as ReleaseTickBar,
  type ReleaseTickBarProps,
} from "./app/components/project/releases/ReleaseTickBar.tsx";
export {
  BUCKET_FILL,
  BUCKET_ICONS,
  BUCKET_ICON_CLASS,
  BUCKET_LABEL_KEYS,
  BUCKET_ORDER,
  type ReleaseBucket,
  type ReleaseBucketLabelKey,
  type ReleaseBuckets,
  questBucket,
  questStatus,
  releaseBuckets,
} from "./app/components/project/releases/releaseBuckets.ts";
export {
  type ReleaseBump,
  type ReleaseBumpSubject,
  releaseBumps,
  suggestedReleaseTag,
} from "./app/components/project/releases/releaseBumps.ts";
export {
  CLUSTER_GAP_X,
  CLUSTER_GAP_Y,
  CLUSTER_HEADER,
  CLUSTER_PAD,
  type ReleaseFlowEpicGroup,
  type ReleaseFlowGroup,
  ReleaseFlowLayout,
  type ReleaseFlowMap,
  TRACK_GAP,
} from "./app/components/project/releases/releaseFlowLayout.ts";
export {
  type ReleaseState,
  type ReleaseStateLabelKey,
  STATE_ICONS,
  STATE_LABEL_KEYS,
  STATE_TONE,
  releaseState,
} from "./app/components/project/releases/releaseState.ts";
export {
  type CountLabelKey,
  useCountLabel,
} from "./app/components/project/releases/useCountLabel.ts";
export { useDashboardReleaseOptions } from "./app/components/project/releases/useDashboardReleaseOptions.ts";
export {
  type DeleteRelease,
  useDeleteRelease,
} from "./app/components/project/releases/useDeleteRelease.ts";
export { useReleaseCascadeToast } from "./app/components/project/releases/useReleaseCascadeToast.ts";
export { useReleaseReferences } from "./app/components/project/releases/useReleaseReferences.ts";
export {
  type SetDefaultRelease,
  useSetDefaultRelease,
} from "./app/components/project/releases/useSetDefaultRelease.ts";
export type { ReportsMembersProps } from "./app/components/project/reports/ReportsMembers.client.tsx";
export type { ReportsOverviewProps } from "./app/components/project/reports/ReportsOverview.client.tsx";
export type { ReportsQuestsProps } from "./app/components/project/reports/ReportsQuests.client.tsx";
export type { ProjectRoadmapProps } from "./app/components/project/roadmap/ProjectRoadmap.tsx";
export {
  default as RoadmapEpicRow,
  type RoadmapEpicRowProps,
} from "./app/components/project/roadmap/RoadmapEpicRow.tsx";
export {
  default as RoadmapEpicRowSegment,
  type RoadmapEpicRowSegmentProps,
} from "./app/components/project/roadmap/RoadmapEpicRowSegment.tsx";
export {
  default as RoadmapReleaseCard,
  type RoadmapReleaseCardProps,
} from "./app/components/project/roadmap/RoadmapReleaseCard.tsx";
export {
  default as RoadmapShippedRow,
  type RoadmapShippedRowProps,
} from "./app/components/project/roadmap/RoadmapShippedRow.tsx";
export {
  default as AreaMergeDialog,
  type AreaMergeDialogProps,
} from "./app/components/project/settings/AreaMergeDialog.tsx";
export {
  default as AreaRenameDialog,
  type AreaRenameDialogProps,
} from "./app/components/project/settings/AreaRenameDialog.tsx";
export {
  default as ProjectSettingsAreaDescription,
  type ProjectSettingsAreaDescriptionProps,
} from "./app/components/project/settings/ProjectSettingsAreaDescription.tsx";
export {
  default as ProjectSettingsAreaHeader,
  type ProjectSettingsAreaHeaderProps,
} from "./app/components/project/settings/ProjectSettingsAreaHeader.tsx";
export type { ProjectSettingsAreaPageProps } from "./app/components/project/settings/ProjectSettingsAreaPage.tsx";
export {
  default as ProjectSettingsAreaQuests,
  type ProjectSettingsAreaQuestsProps,
} from "./app/components/project/settings/ProjectSettingsAreaQuests.tsx";
export {
  default as ProjectSettingsAreaStats,
  type ProjectSettingsAreaStatsProps,
} from "./app/components/project/settings/ProjectSettingsAreaStats.tsx";
export type { ProjectSettingsAreasPageProps } from "./app/components/project/settings/ProjectSettingsAreasPage.tsx";
export { default as ProjectSettingsRoadmapSection } from "./app/components/project/settings/ProjectSettingsRoadmapSection.tsx";
export { default as ProjectSettingsTagColors } from "./app/components/project/settings/ProjectSettingsTagColors.tsx";
export { KanbanColumnOrder } from "./app/components/project/settings/kanbanColumnOrder.ts";
export {
  AREA_DOT_CLASS,
  AreaDotColor,
  TAG_CHIP_CLASS,
  TAG_CHIP_FALLBACK,
} from "./app/components/shared/areaColor.ts";
export { useQuestImageUpload } from "./app/components/shared/markdown-editor/useQuestImageUpload.ts";
export {
  type CompleteQuestBody,
  type QuestMutations,
  useQuestMutations,
} from "./app/components/shared/useQuestMutations.ts";
export { WorkProjectLoader } from "./app/loaders/WorkProjectLoader.ts";
export { epicActivatePromptDefault } from "./app/prompts/epicActivatePrompt.ts";
export { epicReviewPromptDefault } from "./app/prompts/epicReviewPrompt.ts";
export { feedbackLoopPromptDefault } from "./app/prompts/feedbackLoopPrompt.ts";
export { feedbackWorkPromptDefault } from "./app/prompts/feedbackWorkPrompt.ts";
export { questLoopPromptDefault } from "./app/prompts/questLoopPrompt.ts";
export { questWorkPromptDefault } from "./app/prompts/questWorkPrompt.ts";
export { WorkShell } from "./app/shell/WorkShell.ts";
