import { LoreCoreWeb } from "@lore/core/web";
import { $module } from "alepha";

import { folioTreeCollapsedAtom } from "./app/atoms/folioTreeCollapsedAtom.ts";
import { projectDirectoriesAtom } from "./app/atoms/projectDirectoriesAtom.ts";
import { KnowledgeRouter } from "./app/KnowledgeRouter.ts";
import { KnowledgeShell } from "./app/shell/KnowledgeShell.ts";

/**
 * The browser-safe half of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreKnowledgeWeb = $module({
  name: "lore.knowledge.web",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreWeb],
  atoms: [projectDirectoriesAtom, folioTreeCollapsedAtom],
  register(alepha) {
    // Injected rather than listed in `services`: a listed service is tagged
    // with this module, and injecting it anywhere (a spec, a component
    // importing it from the barrel) would then register the whole module.
    // The pages, and Knowledge's part of the project shell (sidebar,
    // settings, create menu, references, the epic's Folios tab, the document
    // sink) on core's registries, which nothing else would construct.
    alepha.inject(KnowledgeRouter);
    alepha.inject(KnowledgeShell);
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { KnowledgeRouter } from "./app/KnowledgeRouter.ts";
export { currentFolioAttachmentsAtom } from "./app/atoms/currentFolioAttachmentsAtom.ts";
export { folioTextSizeAtom } from "./app/atoms/folioTextSizeAtom.ts";
export { folioTreeCollapsedAtom } from "./app/atoms/folioTreeCollapsedAtom.ts";
export { folioTreeSeedAtom } from "./app/atoms/folioTreeSeedAtom.ts";
export { projectDirectoriesAtom } from "./app/atoms/projectDirectoriesAtom.ts";
export { userFoliosAtom } from "./app/atoms/userFoliosAtom.ts";
export type { FolioCreatePageProps } from "./app/components/folios/FolioCreatePage.tsx";
export {
  default as FolioPassphraseDialog,
  type FolioPassphraseDialogProps,
} from "./app/components/folios/FolioPassphraseDialog.tsx";
export type { FolioWorkspaceProps } from "./app/components/folios/editor/FolioWorkspace.tsx";
export {
  default as FolioWorkspaceContent,
  type FolioWorkspaceContentProps,
} from "./app/components/folios/editor/FolioWorkspaceContent.tsx";
export {
  default as FolioWorkspaceEmpty,
  type FolioWorkspaceEmptyProps,
} from "./app/components/folios/editor/FolioWorkspaceEmpty.tsx";
export {
  default as FolioWorkspaceShell,
  type FolioWorkspaceShellProps,
} from "./app/components/folios/editor/FolioWorkspaceShell.tsx";
export {
  FolioWorkspaceShellContext,
  type FolioWorkspaceShellValue,
} from "./app/components/folios/editor/FolioWorkspaceShellContext.ts";
export {
  default as FolioDocument,
  type FolioDocumentProps,
} from "./app/components/folios/editor/document/FolioDocument.tsx";
export {
  default as FolioEmptyState,
  type FolioEmptyStateProps,
} from "./app/components/folios/editor/document/FolioEmptyState.tsx";
export {
  default as FolioFindBar,
  type FolioFindBarProps,
} from "./app/components/folios/editor/document/FolioFindBar.tsx";
export {
  default as FolioLockedPanel,
  type FolioLockedPanelProps,
} from "./app/components/folios/editor/document/FolioLockedPanel.tsx";
export {
  default as FolioMoveDialog,
  type FolioMoveDialogProps,
} from "./app/components/folios/editor/document/FolioMoveDialog.tsx";
export {
  default as FolioSummaryField,
  type FolioSummaryFieldProps,
} from "./app/components/folios/editor/document/FolioSummaryField.tsx";
export {
  type FolioFindMatch,
  folioFindMatches,
  stepFolioMatch,
} from "./app/components/folios/editor/document/folioFindMatches.ts";
export {
  type FolioMarkdownExportInput,
  folioExportFilename,
  folioMarkdownExport,
  triggerFolioDownload,
} from "./app/components/folios/editor/document/folioMarkdownExport.ts";
export {
  type FolioZipAttachment,
  folioZipEntries,
} from "./app/components/folios/editor/document/folioZipExport.ts";
export {
  type FolioFindState,
  useFolioFind,
} from "./app/components/folios/editor/document/useFolioFind.ts";
export {
  default as FolioAttachmentsTab,
  type FolioAttachmentsTabProps,
} from "./app/components/folios/editor/inspector/FolioAttachmentsTab.tsx";
export {
  default as FolioHistoryTab,
  type FolioHistoryTabProps,
} from "./app/components/folios/editor/inspector/FolioHistoryTab.tsx";
export {
  default as FolioInspector,
  type FolioInspectorProps,
  type FolioInspectorTab,
} from "./app/components/folios/editor/inspector/FolioInspector.tsx";
export {
  default as FolioInspectorRail,
  type FolioInspectorRailProps,
} from "./app/components/folios/editor/inspector/FolioInspectorRail.tsx";
export {
  default as FolioLinksTab,
  type FolioLinksTabProps,
} from "./app/components/folios/editor/inspector/FolioLinksTab.tsx";
export {
  default as FolioOutlineTab,
  type FolioOutlineTabProps,
} from "./app/components/folios/editor/inspector/FolioOutlineTab.tsx";
export {
  default as FolioPinnedBudget,
  type FolioPinnedBudgetProps,
} from "./app/components/folios/editor/inspector/FolioPinnedBudget.tsx";
export {
  type FolioOutlineHeading,
  markdownOutline,
} from "./app/components/folios/editor/inspector/markdownOutline.ts";
export {
  type FolioOutlineDomHeading,
  resolveHeadingIndex,
} from "./app/components/folios/editor/inspector/resolveHeadingIndex.ts";
export {
  default as FolioMenubar,
  type FolioMenubarProps,
} from "./app/components/folios/editor/menubar/FolioMenubar.tsx";
export {
  FOLIO_MENUS,
  type FolioActionId,
  type FolioActionState,
  type FolioMenu,
  type FolioMenuEntry,
  type FolioMenuItem,
  type FolioMenuRadioGroup,
  editorOwnsBinding,
  folioMenuItems,
  folioShortcutBindings,
  folioShortcutGlyph,
  isFolioActionEnabled,
  isFolioTextSizeEnabled,
} from "./app/components/folios/editor/menubar/folioMenubarModel.ts";
export { useFolioShortcuts } from "./app/components/folios/editor/menubar/useFolioShortcuts.ts";
export {
  default as FolioTree,
  type FolioTreeActions,
  type FolioTreeProps,
} from "./app/components/folios/editor/tree/FolioTree.tsx";
export {
  default as FolioTreeContextMenu,
  type FolioTreeContextMenuProps,
} from "./app/components/folios/editor/tree/FolioTreeContextMenu.tsx";
export {
  default as FolioTreeDirectoryIcon,
  type FolioTreeDirectoryIconProps,
} from "./app/components/folios/editor/tree/FolioTreeDirectoryIcon.tsx";
export {
  default as FolioTreeRail,
  type FolioTreeRailProps,
} from "./app/components/folios/editor/tree/FolioTreeRail.tsx";
export {
  default as FolioTreeRootContextMenu,
  type FolioTreeRootContextMenuProps,
} from "./app/components/folios/editor/tree/FolioTreeRootContextMenu.tsx";
export { resolveDirectoryBadge } from "./app/components/folios/editor/tree/folioDirectoryIcons.ts";
export {
  type FolioDropPosition,
  type FolioTreeData,
  type FolioTreeKind,
  type FolioTreeNode,
  type FolioTreeRow,
  asFolioNode,
  buildFolioTree,
  findFolioNode,
  flattenFolioTree,
} from "./app/components/folios/editor/tree/folioTree.ts";
export {
  type FolioTreeCommands,
  type FolioTreeState,
  type FolioTreeVerbs,
  type UseFolioTreeModelInput,
  useFolioTreeModel,
} from "./app/components/folios/editor/tree/useFolioTreeModel.ts";
export {
  type FolioActionHandlers,
  type UseFolioActionsInput,
  type UseFolioActionsResult,
  useFolioActions,
} from "./app/components/folios/editor/useFolioActions.ts";
export {
  type UseFolioAutoSaveInput,
  useFolioAutoSave,
} from "./app/components/folios/editor/useFolioAutoSave.ts";
export {
  type FolioDraft,
  type FolioDraftValues,
  folioDraftSchema,
  sameValues,
  useFolioDraft,
} from "./app/components/folios/editor/useFolioDraft.ts";
export {
  type FolioPanesState,
  TREE_DEFAULT_WIDTH,
  TREE_MAX_WIDTH,
  TREE_MIN_WIDTH,
  useFolioPanes,
} from "./app/components/folios/editor/useFolioPanes.ts";
export {
  default as EpicFolioPicker,
  type EpicFolioPickerProps,
} from "./app/components/folios/epic/EpicFolioPicker.tsx";
export {
  default as EpicFoliosList,
  type EpicFoliosListProps,
} from "./app/components/folios/epic/EpicFoliosList.tsx";
export type { EpicFoliosPanelProps } from "./app/components/folios/epic/EpicFoliosPanel.tsx";
export { useFiledFolios } from "./app/components/folios/epic/useFiledFolios.ts";
export {
  folioAssetEmbed,
  folioAssetPath,
  folioAssetReferenceForms,
  rewriteFolioAssetReferences,
} from "./app/components/folios/folioAssetReference.ts";
export { FOLIO_IMAGE_MAX_WIDTH } from "./app/components/folios/folioImageBounds.ts";
export {
  ensureProtectedKeysAutoLock,
  forgetAllProtectedKeys,
  forgetProtectedKey,
  getProtectedKey,
  onProtectedKeysChange,
  rememberProtectedKey,
} from "./app/components/folios/protectedFolioKeys.ts";
export { useFolioElementImageUpload } from "./app/components/folios/useFolioElementImageUpload.ts";
export { useFolioReferences } from "./app/components/folios/useFolioReferences.ts";
export { useFolioImageUpload } from "./app/components/shared/markdown-editor/useFolioImageUpload.ts";
export { KnowledgeShell } from "./app/shell/KnowledgeShell.ts";
