import { LoreCoreWeb } from "@lore/core/web";
import { $module } from "alepha";

import { folioTreeCollapsedAtom } from "./app/atoms/folioTreeCollapsedAtom.ts";
import { projectDirectoriesAtom } from "./app/atoms/projectDirectoriesAtom.ts";
import { KnowledgeRouter } from "./app/KnowledgeRouter.ts";
import { KnowledgeShell } from "./app/shell/KnowledgeShell.ts";

/**
 * The browser-safe half of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreKnowledgeWeb = $module({
  name: "lore.knowledge.web",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreWeb],
  atoms: [projectDirectoriesAtom, folioTreeCollapsedAtom],
  register(alepha) {
    // Injected rather than listed in `services`: a listed service is tagged
    // with this module, and injecting it anywhere (a spec, a component
    // importing it from the barrel) would then register the whole module.
    // The pages, and Knowledge's part of the project shell (sidebar,
    // settings, create menu, references, the epic's Folios tab, the document
    // sink) on core's registries, which nothing else would construct.
    alepha.inject(KnowledgeRouter);
    alepha.inject(KnowledgeShell);
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { KnowledgeRouter } from "./app/KnowledgeRouter.ts";
export {
  folioFindMatches,
  stepFolioMatch,
} from "./app/components/folios/editor/document/folioFindMatches.ts";
export { folioMarkdownExport } from "./app/components/folios/editor/document/folioMarkdownExport.ts";
export { folioZipEntries } from "./app/components/folios/editor/document/folioZipExport.ts";
export {
  type FolioOutlineHeading,
  markdownOutline,
} from "./app/components/folios/editor/inspector/markdownOutline.ts";
export {
  type FolioOutlineDomHeading,
  resolveHeadingIndex,
} from "./app/components/folios/editor/inspector/resolveHeadingIndex.ts";
export {
  FOLIO_MENUS,
  folioMenuItems,
  folioShortcutBindings,
  isFolioActionEnabled,
} from "./app/components/folios/editor/menubar/folioMenubarModel.ts";
export {
  buildFolioTree,
  findFolioNode,
} from "./app/components/folios/editor/tree/folioTree.ts";
export { default as EpicFoliosList } from "./app/components/folios/epic/EpicFoliosList.tsx";
export {
  folioAssetEmbed,
  folioAssetPath,
} from "./app/components/folios/folioAssetReference.ts";
export { FOLIO_IMAGE_MAX_WIDTH } from "./app/components/folios/folioImageBounds.ts";
export { KnowledgeShell } from "./app/shell/KnowledgeShell.ts";
