-- `invitations` moved into `alepha/api/invitations`. Two things changed with it:
--
-- 1. `organization_id` was added, nullable, following the `parameters`
--    precedent. Lore resolves no tenant, so every row keeps being written NULL
--    with the historic global semantics. That is the one statement below.
--
-- 2. The two foreign keys into `users` (`invited_by` ON DELETE CASCADE, and
--    `resolved_by`) were dropped from the ENTITY, because no framework module
--    references another module's table -- `api/keys` and `api/audits` both
--    record a user id as a bare uuid for the same reason.
--
-- ⚠️ Statement 2 is deliberately NOT in this file, and the drift that leaves
-- is deliberate too. drizzle-kit generated the standard SQLite rebuild for it
-- (CREATE __new / INSERT SELECT / `DROP TABLE invitations` / RENAME), and on
-- D1 a `DROP TABLE` runs its CASCADEs for real -- the failure mode that wiped
-- lore-production in 2026-05. `invitations` is nobody's CASCADE parent today,
-- so that rebuild would probably have been survivable; "probably survivable"
-- is not a reason to run a rebuild that buys nothing.
--
-- What it would buy is a physical table that agrees with the snapshot. What it
-- costs is a rebuild, plus the loss of `ON DELETE CASCADE` on `invited_by`,
-- which is real behaviour Lore has today. So the physical table keeps both
-- foreign keys while the snapshot no longer declares them. Nothing can trip
-- over this: drizzle diffs the ENTITY against the SNAPSHOT and never looks at
-- the live database, and the cascade that survives is the one that was already
-- there. The next migration that genuinely has to rebuild this table will
-- resolve the drift on its own, by building it from the snapshot.
--
-- Same precedent, same verdict as `projects.features`'s stale DEFAULT and
-- `sigils.name`'s physical nullability. See apps/lore/CLAUDE.md, "Migration
-- safety on D1".
ALTER TABLE `invitations` ADD `organization_id` text;
