import { LoreCoreMcp } from "@lore/core/mcp";
import { $module } from "alepha";

import { KnowledgeProjectContext } from "./services/KnowledgeProjectContext.ts";
import { FolioTools } from "./tools/FolioTools.ts";

/**
 * The MCP tools and resources of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names.
 *
 * Registered by `apps/lore/src/main.server.ts` beside `LoreKnowledgeApi`.
 *
 * @module
 */
export const LoreKnowledgeMcp = $module({
  name: "lore.knowledge.mcp",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreMcp],
  services: [FolioTools, KnowledgeProjectContext],
});

// ---- re-exports, generated by the extraction (#E75) ----

export { KnowledgeProjectContext } from "./services/KnowledgeProjectContext.ts";
export { FolioTools } from "./tools/FolioTools.ts";
