import { randomBytes } from "node:crypto";
import { $inject, type Static, t } from "alepha";
import { $logger } from "alepha/logger";
import { $repository } from "alepha/orm";
import { $secure } from "alepha/security";
import { $action, NotFoundError, okSchema } from "alepha/server";
import { SIGIL_KINDS, type Sigil, sigils } from "../entities/sigils.ts";
import { AppSecurityProvider } from "../providers/AppSecurityProvider.ts";

/**
 * A sigil resource as exposed to the owner's Settings page. NB: the
 * `ingestKey` column is deliberately ABSENT — it is a server-held secret
 * and the UI never needs it (the copy-snippet uses only the public `id`).
 */
const sigilResourceSchema = t.object({
  id: t.uuid(),
  campaignId: t.integer(),
  label: t.string(),
  kinds: t.array(t.string()),
  excludedPaths: t.array(t.string()),
  createdAt: t.datetime(),
});

/**
 * A sigil as exposed to the owner's Settings page — the `ingestKey` secret
 * is deliberately absent (see `sigilResourceSchema`). `toResource` is
 * annotated with this type so a field mismatch fails at compile time.
 */
export type SigilResource = Static<typeof sigilResourceSchema>;

const sigilBodySchema = t.object({
  label: t.string({ minLength: 1, maxLength: 200 }),
  kinds: t.optional(
    t.array(t.enum([...SIGIL_KINDS], { mode: "text" }), { maxItems: 10 }),
  ),
  excludedPaths: t.optional(
    t.array(t.string({ maxLength: 200 }), { maxItems: 50 }),
  ),
});

/**
 * Owner-facing CRUD surface for sigils — the scoped, revocable identifiers
 * that let a partner server forward telemetry and petitions to Lore via
 * the trusted server-to-server ingest endpoints.
 *
 * Every endpoint is owner-gated via `AppSecurityProvider.assertOwner`,
 * mirroring `PetitionController`'s owner endpoints.
 */
export class SigilController {
  protected log = $logger();
  protected sigils = $repository(sigils);
  protected security = $inject(AppSecurityProvider);

  /**
   * Create a sigil for a campaign. The `id` (public, embedded in the
   * partner's `<script>` src) is auto-generated by the ORM as a UUID;
   * the `ingestKey` (secret, baked into the served `.js`) is minted
   * here as a separate random hex string.
   */
  createSigil = $action({
    use: [$secure({ permissions: ["campaign:update"] })],
    method: "POST",
    path: "/c/:campaignId/sigils",
    schema: {
      params: t.object({ campaignId: t.integer() }),
      body: sigilBodySchema,
      response: sigilResourceSchema,
    },
    handler: async ({ params, body, user }) => {
      await this.security.assertOwner(params.campaignId, user);

      const created = await this.sigils.create({
        campaignId: params.campaignId,
        label: body.label,
        allowedOrigins: [],
        kinds: body.kinds ?? [],
        excludedPaths: body.excludedPaths ?? [],
        ingestKey: this.generateIngestKey(),
        createdBy: user.id,
      });

      return this.toResource(created);
    },
  });

  /**
   * List every sigil for a campaign. Owner-only.
   *
   * Sigils are HARD-deleted (see {@link deleteSigil}) so no row ever
   * carries a non-null `revokedAt` — a plain `findMany` returns the full
   * live set without needing `force: true`.
   */
  listSigils = $action({
    use: [$secure({ permissions: ["campaign:read"] })],
    method: "GET",
    path: "/c/:campaignId/sigils",
    schema: {
      params: t.object({ campaignId: t.integer() }),
      response: t.object({ items: t.array(sigilResourceSchema) }),
    },
    handler: async ({ params, user }) => {
      await this.security.assertOwner(params.campaignId, user);

      const items = await this.sigils.findMany({
        where: { campaignId: { eq: params.campaignId } },
        orderBy: [{ column: "createdAt", direction: "desc" }],
      });

      return { items: items.map((s) => this.toResource(s)) };
    },
  });

  /**
   * Update a sigil's `label` / `kinds` / `excludedPaths`. The public
   * `id`, the secret `ingestKey`, and the `campaignId` are NOT mutable —
   * changing those three columns never reissues the sigil, so the
   * partner's `<script>` tag keeps working unchanged. Owner-only.
   */
  updateSigil = $action({
    use: [$secure({ permissions: ["campaign:update"] })],
    method: "PATCH",
    path: "/c/:campaignId/sigils/:id",
    schema: {
      params: t.object({ campaignId: t.integer(), id: t.uuid() }),
      body: sigilBodySchema,
      response: sigilResourceSchema,
    },
    handler: async ({ params, body, user }) => {
      await this.security.assertOwner(params.campaignId, user);
      const sigil = await this.loadSigil(params.campaignId, params.id);

      await this.sigils.updateById(sigil.id, {
        label: body.label,
        kinds: body.kinds ?? [],
        excludedPaths: body.excludedPaths ?? [],
      });

      const updated = await this.loadSigil(params.campaignId, params.id);
      return this.toResource(updated);
    },
  });

  /**
   * Delete a sigil — a genuine HARD delete: the row is removed. The
   * `sigil_blights` / `sigil_views` children cascade-delete via their FK
   * `onDelete: cascade` — intended (a deleted sigil keeps no data).
   * Owner-only.
   */
  deleteSigil = $action({
    use: [$secure({ permissions: ["campaign:delete"] })],
    method: "DELETE",
    path: "/c/:campaignId/sigils/:id",
    schema: {
      params: t.object({ campaignId: t.integer(), id: t.uuid() }),
      response: okSchema,
    },
    handler: async ({ params, user }) => {
      await this.security.assertOwner(params.campaignId, user);
      const sigil = await this.loadSigil(params.campaignId, params.id);

      // `sigils` carries a vestigial `db.deletedAt()` column, so the ORM
      // would soft-delete by default — `force: true` makes this a real
      // row removal.
      await this.sigils.deleteById(sigil.id, { force: true });
      return { ok: true };
    },
  });

  /**
   * Regenerate a sigil's `ingestKey`. The public `id` is left untouched
   * — the partner's `<script>` snippet keeps working; only the secret
   * baked into the served `.js` changes. Owner-only.
   */
  rotateSigilKey = $action({
    use: [$secure({ permissions: ["campaign:update"] })],
    method: "POST",
    path: "/c/:campaignId/sigils/:id/rotate-key",
    schema: {
      params: t.object({ campaignId: t.integer(), id: t.uuid() }),
      response: t.object({ ok: t.boolean(), id: t.uuid() }),
    },
    handler: async ({ params, user }) => {
      await this.security.assertOwner(params.campaignId, user);
      const sigil = await this.loadSigil(params.campaignId, params.id);

      await this.sigils.updateById(sigil.id, {
        ingestKey: this.generateIngestKey(),
      });
      return { ok: true, id: sigil.id };
    },
  });

  /**
   * Load a sigil by id, asserting it belongs to the expected campaign.
   * Sigils are hard-deleted, so a missing row is genuinely gone — a plain
   * `findOne` is correct and a not-found is a clean 404.
   */
  protected async loadSigil(campaignId: number, id: string): Promise<Sigil> {
    const sigil = await this.sigils.findOne({
      where: { id: { eq: id }, campaignId: { eq: campaignId } },
    });
    if (!sigil) {
      throw new NotFoundError("Sigil not found");
    }
    return sigil;
  }

  /**
   * Strip the `ingestKey` secret before a sigil row leaves the server.
   */
  protected toResource(sigil: Sigil): SigilResource {
    return {
      id: sigil.id,
      campaignId: sigil.campaignId,
      label: sigil.label,
      kinds: sigil.kinds ?? [],
      excludedPaths: sigil.excludedPaths ?? [],
      createdAt: sigil.createdAt,
    };
  }

  /**
   * Mint a fresh `ingestKey` — a 32-byte random secret, hex-encoded.
   * Separate from the public sigil `id`; rotatable without reissuing it.
   */
  protected generateIngestKey(): string {
    return randomBytes(32).toString("hex");
  }
}
