import { randomBytes } from "node:crypto";
import { $inject, type Static, t } from "alepha";
import { $logger } from "alepha/logger";
import { $repository } from "alepha/orm";
import { $secure } from "alepha/security";
import { $action, NotFoundError, okSchema } from "alepha/server";
import { SIGIL_KINDS, type Sigil, sigils } from "../entities/sigils.ts";
import { AppSecurityProvider } from "../providers/AppSecurityProvider.ts";

/**
 * A sigil resource as exposed to the owner's Settings page. NB: the
 * `ingestKey` column is deliberately ABSENT — it is a vestigial column that
 * gates nothing, and the UI never needs it (the copy-snippet and the ingest
 * path both key off the `id`).
 */
const sigilResourceSchema = t.object({
  id: t.uuid(),
  campaignId: t.integer(),
  label: t.string(),
  createdAt: t.datetime(),
});

/**
 * A sigil as exposed to the owner's Settings page — the vestigial
 * `ingestKey` column is deliberately absent (see `sigilResourceSchema`).
 * `toResource` is annotated with this type so a field mismatch fails at
 * compile time.
 */
export type SigilResource = Static<typeof sigilResourceSchema>;

const sigilBodySchema = t.object({
  label: t.string({ minLength: 1, maxLength: 200 }),
  /**
   * Server-side authorization kinds. Not exposed in the UI / MCP (a sigil is
   * just a named id there); omitting it grants ALL kinds. Kept on the API for
   * programmatic callers that want to scope a sigil's ingest gate.
   */
  kinds: t.optional(
    t.array(t.enum([...SIGIL_KINDS], { mode: "text" }), { maxItems: 10 }),
  ),
});

/**
 * Owner-facing CRUD surface for sigils — the scoped, revocable identifiers
 * that let a partner server forward telemetry and petitions to Lore via
 * the trusted server-to-server ingest endpoints.
 *
 * Every endpoint is owner-gated via `AppSecurityProvider.assertOwner`,
 * mirroring `PetitionController`'s owner endpoints.
 */
export class SigilController {
  protected log = $logger();
  protected sigils = $repository(sigils);
  protected security = $inject(AppSecurityProvider);

  /**
   * Create a sigil for a campaign. The `id` is auto-generated by the ORM as
   * a UUID and is the sole credential on the trusted server-to-server ingest
   * path (`POST /sigils/:id/ingest`). The `ingestKey` column is vestigial
   * (no live code path reads it — see the entity doc) but `NOT NULL`, so a
   * random hex value is still minted here to satisfy the constraint.
   */
  createSigil = $action({
    use: [$secure({ permissions: ["campaign:update"] })],
    method: "POST",
    path: "/c/:campaignId/sigils",
    schema: {
      params: t.object({ campaignId: t.integer() }),
      body: sigilBodySchema,
      response: sigilResourceSchema,
    },
    handler: async ({ params, body, user }) => {
      await this.security.assertOwner(params.campaignId, user);

      const created = await this.sigils.create({
        campaignId: params.campaignId,
        label: body.label,
        allowedOrigins: [],
        // Capabilities are no longer scoped per-sigil in the UI — the partner
        // app picks features via `SIGIL_FEATURES`. Omitted `kinds` grants ALL;
        // campaign features + the partner env do the real gating.
        kinds: body.kinds ?? [...SIGIL_KINDS],
        ingestKey: this.generateIngestKey(),
        createdBy: user.id,
      });

      return this.toResource(created);
    },
  });

  /**
   * List every sigil for a campaign. Owner-only.
   *
   * Sigils are HARD-deleted (see {@link deleteSigil}) so no row ever
   * carries a non-null `revokedAt` — a plain `findMany` returns the full
   * live set without needing `force: true`.
   */
  listSigils = $action({
    use: [$secure({ permissions: ["campaign:read"] })],
    method: "GET",
    path: "/c/:campaignId/sigils",
    schema: {
      params: t.object({ campaignId: t.integer() }),
      response: t.object({ items: t.array(sigilResourceSchema) }),
    },
    handler: async ({ params, user }) => {
      await this.security.assertOwner(params.campaignId, user);

      const items = await this.sigils.findMany({
        where: { campaignId: { eq: params.campaignId } },
        orderBy: [{ column: "createdAt", direction: "desc" }],
      });

      return { items: items.map((s) => this.toResource(s)) };
    },
  });

  /**
   * Rename a sigil (its `label`). The `id` and `campaignId` are NOT mutable —
   * the `id` is the ingest credential, so it never changes here and the
   * partner's existing ingest calls keep working. Owner-only.
   */
  updateSigil = $action({
    use: [$secure({ permissions: ["campaign:update"] })],
    method: "PATCH",
    path: "/c/:campaignId/sigils/:id",
    schema: {
      params: t.object({ campaignId: t.integer(), id: t.uuid() }),
      body: sigilBodySchema,
      response: sigilResourceSchema,
    },
    handler: async ({ params, body, user }) => {
      await this.security.assertOwner(params.campaignId, user);
      const sigil = await this.loadSigil(params.campaignId, params.id);

      await this.sigils.updateById(sigil.id, { label: body.label });

      const updated = await this.loadSigil(params.campaignId, params.id);
      return this.toResource(updated);
    },
  });

  /**
   * Delete a sigil — a genuine HARD delete: the row is removed. The
   * `sigil_blights` / `sigil_views` children cascade-delete via their FK
   * `onDelete: cascade` — intended (a deleted sigil keeps no data).
   * Owner-only.
   */
  deleteSigil = $action({
    use: [$secure({ permissions: ["campaign:delete"] })],
    method: "DELETE",
    path: "/c/:campaignId/sigils/:id",
    schema: {
      params: t.object({ campaignId: t.integer(), id: t.uuid() }),
      response: okSchema,
    },
    handler: async ({ params, user }) => {
      await this.security.assertOwner(params.campaignId, user);
      const sigil = await this.loadSigil(params.campaignId, params.id);

      // `sigils` carries a vestigial `db.deletedAt()` column, so the ORM
      // would soft-delete by default — `force: true` makes this a real
      // row removal.
      await this.sigils.deleteById(sigil.id, { force: true });
      return { ok: true };
    },
  });

  /**
   * Load a sigil by id, asserting it belongs to the expected campaign.
   * Sigils are hard-deleted, so a missing row is genuinely gone — a plain
   * `findOne` is correct and a not-found is a clean 404.
   */
  protected async loadSigil(campaignId: number, id: string): Promise<Sigil> {
    const sigil = await this.sigils.findOne({
      where: { id: { eq: id }, campaignId: { eq: campaignId } },
    });
    if (!sigil) {
      throw new NotFoundError("Sigil not found");
    }
    return sigil;
  }

  /**
   * Project a sigil row into the owner-facing resource. The vestigial
   * `ingestKey` column is never carried over (it gates nothing).
   */
  protected toResource(sigil: Sigil): SigilResource {
    return {
      id: sigil.id,
      campaignId: sigil.campaignId,
      label: sigil.label,
      createdAt: sigil.createdAt,
    };
  }

  /**
   * Mint a value for the vestigial `NOT NULL` `ingestKey` column — a 32-byte
   * random hex string. Nothing reads it; it exists only to satisfy the
   * not-null constraint on insert (the column is kept because dropping it is
   * a D1 cascade bomb — see the entity doc).
   */
  protected generateIngestKey(): string {
    return randomBytes(32).toString("hex");
  }
}
