import { LoreCoreApi } from "@lore/core/api";
import { $module } from "alepha";

import { DirectoryController } from "./controllers/DirectoryController.ts";
import { FolioAttachmentController } from "./controllers/FolioAttachmentController.ts";
import { FolioController } from "./controllers/FolioController.ts";
import { DirectoryResourceKind } from "./resources/DirectoryResourceKind.ts";
import { FolioResourceKind } from "./resources/FolioResourceKind.ts";
import { FolioAttachmentService } from "./services/FolioAttachmentService.ts";
import { FolioDirectoryService } from "./services/FolioDirectoryService.ts";
import { FolioHistoryService } from "./services/FolioHistoryService.ts";
import { FolioNameService } from "./services/FolioNameService.ts";
import { KnowledgeFileAccess } from "./services/KnowledgeFileAccess.ts";

/**
 * The server half of `@lore/knowledge`, Lore as Obsidian: folios, their directories, attachments, revisions and names.
 *
 * It depends on `@lore/core` only: a feature that spans two modules goes through a core registry or a core link, never through an import of another feature module (`check:conventions`).
 *
 * Registered by `apps/lore/src/main.server.ts`, after every entry-level
 * substitution.
 *
 * @module
 */
export const LoreKnowledgeApi = $module({
  name: "lore.knowledge.api",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreApi],
  services: [
    FolioNameService,
    FolioDirectoryService,
    FolioAttachmentService,
    FolioHistoryService,
    FolioResourceKind,
    DirectoryResourceKind,
    KnowledgeFileAccess,
    FolioController,
    DirectoryController,
    FolioAttachmentController,
  ],
});

// ---- re-exports, generated by the extraction (#E75) ----

export { folioHistoryAtom } from "./atoms/folioHistoryAtom.ts";
export { DirectoryController } from "./controllers/DirectoryController.ts";
export { FolioAttachmentController } from "./controllers/FolioAttachmentController.ts";
export { FolioController } from "./controllers/FolioController.ts";
export { FolioAttachmentService } from "./services/FolioAttachmentService.ts";
export { FolioDirectoryService } from "./services/FolioDirectoryService.ts";
export {
  type AppendedRevision,
  FolioHistoryService,
} from "./services/FolioHistoryService.ts";
export { FolioNameService } from "./services/FolioNameService.ts";
export { PinnedFolioFolder } from "./services/PinnedFolioFolder.ts";
