/**
 * The browser-safe schemas of `@lore/core`, the glue: projects, capabilities, ranks and permissions, notifications, audits, the resource registry and its link graph, search, the dashboard, reports, agent prompts and the web shell.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export {
  type CapabilityDescriptor,
  type CapabilityOptionDescriptor,
  CapabilityRegistry,
} from "../api/schemas/CapabilityRegistry.ts";
export {
  type DashboardBoard,
  type DashboardCardLink,
  type DashboardCardTarget,
  DashboardMetricCatalog,
  type DashboardMetricDescriptor,
  type DashboardMetricRequirement,
  type DashboardPresentation,
} from "../api/schemas/DashboardMetricCatalog.ts";
export { ProjectSlugService } from "../api/schemas/ProjectSlugService.ts";
export {
  type AdminProjectResource,
  adminProjectResourceSchema,
} from "../api/schemas/adminProjectResourceSchema.ts";
export {
  type AgentPromptKind,
  agentPromptKindSchema,
} from "../api/schemas/agentPromptKindSchema.ts";
export {
  APP_NAME_MAX_LENGTH,
  APP_NAME_PATTERN,
  SIGIL_NAME_PAIR_MAX_LENGTH,
  appNameSchema,
} from "../api/schemas/appNameSchema.ts";
export {
  type AssignedWorkItem,
  assignedWorkItemSchema,
} from "../api/schemas/assignedWorkItemSchema.ts";
export {
  CAPABILITY_KEYS,
  type CapabilityKey,
  capabilityKeySchema,
} from "../api/schemas/capabilityKeySchema.ts";
export {
  type DashboardCardResource,
  dashboardCardResourceSchema,
} from "../api/schemas/dashboardCardResourceSchema.ts";
export {
  type DashboardCardValue,
  dashboardCardValueSchema,
} from "../api/schemas/dashboardCardValueSchema.ts";
export {
  type DashboardScope,
  type DashboardScopeKind,
  dashboardScopeSchema,
} from "../api/schemas/dashboardScopeSchema.ts";
export {
  type ElementKind,
  elementKindSchema,
} from "../api/schemas/elementKindSchema.ts";
export { homeBoardSchema } from "../api/schemas/homeBoardSchema.ts";
export { invitationInboxItemSchema } from "../api/schemas/invitationInboxItemSchema.ts";
export {
  type InvitationTokenPreview,
  invitationTokenPreviewSchema,
} from "../api/schemas/invitationTokenPreviewSchema.ts";
export {
  type KanbanColumnConfigMap,
  type KanbanColumnSettings,
  kanbanColumnConfigSchema,
  kanbanColumnSettingsSchema,
} from "../api/schemas/kanbanColumnSchema.ts";
export {
  type LinkRelation,
  linkRelationSchema,
} from "../api/schemas/linkRelationSchema.ts";
export {
  type LinkSourceKind,
  linkSourceKindSchema,
} from "../api/schemas/linkSourceKindSchema.ts";
export {
  type LinkTargetKind,
  linkTargetKindSchema,
} from "../api/schemas/linkTargetKindSchema.ts";
export {
  type NotificationPreferenceResource,
  notificationPreferenceResourceSchema,
} from "../api/schemas/notificationPreferenceResourceSchema.ts";
export {
  PALETTE_COLORS,
  type PaletteColor,
  paletteColorSchema,
} from "../api/schemas/paletteColorSchema.ts";
export {
  type ProjectActivityRow,
  projectActivityRowSchema,
} from "../api/schemas/projectActivityRowSchema.ts";
export {
  type ProjectCapabilityResource,
  projectCapabilityResourceSchema,
} from "../api/schemas/projectCapabilityResourceSchema.ts";
export {
  type ProjectNameAvailability,
  projectNameAvailabilitySchema,
} from "../api/schemas/projectNameAvailabilitySchema.ts";
export {
  type ProjectPromptResource,
  projectPromptResourceSchema,
} from "../api/schemas/projectPromptResourceSchema.ts";
export { projectRepositoryUrlSchema } from "../api/schemas/projectRepositoryUrlSchema.ts";
export {
  type ProjectOverviewResource,
  type ProjectResource,
  projectOverviewResourceSchema,
  projectResourceSchema,
} from "../api/schemas/projectResourceSchema.ts";
export { projectTitleSchema } from "../api/schemas/projectTitleSchema.ts";
export {
  RELEASE_TAG_MAX_LENGTH,
  RELEASE_TAG_PATTERN,
  releaseTagSchema,
} from "../api/schemas/releaseTagSchema.ts";
export {
  reportsMembersSchema,
  reportsOverviewSchema,
  reportsQuestsSchema,
} from "../api/schemas/reportsSchemas.ts";
export {
  type RoadmapVisibility,
  roadmapVisibilitySchema,
} from "../api/schemas/roadmapVisibilitySchema.ts";
export {
  type SearchHit,
  searchHitSchema,
} from "../api/schemas/searchHitSchema.ts";
export {
  type UpdateNotificationPreferenceBody,
  updateNotificationPreferenceBodySchema,
} from "../api/schemas/updateNotificationPreferenceBodySchema.ts";
export {
  type AttachmentPushResult,
  attachmentPushResultSchema,
} from "../mcp/schemas/attachmentPushResultSchema.ts";
export { DIAGRAM_CAPABILITY } from "../mcp/schemas/diagramCapability.ts";
export { diagramWarningsShape } from "../mcp/schemas/diagramWarningsSchema.ts";
export { entityRefSchema } from "../mcp/schemas/entityRefSchema.ts";
export { epicStatusSchema } from "../mcp/schemas/epicStatusSchema.ts";
export { prioritySchema } from "../mcp/schemas/prioritySchema.ts";
export { projectParamsSchema } from "../mcp/schemas/projectParamsSchema.ts";
export {
  projectActivityParamsSchema,
  projectActivityResultSchema,
  projectContextParamsSchema,
  projectContextResultSchema,
  projectInfoParamsSchema,
  projectInfoResultSchema,
  projectListResultSchema,
} from "../mcp/schemas/projectSchemas.ts";
export { files } from "../api/entities/files.ts";
export { type FolioLink, folioLinks } from "../api/entities/folioLinks.ts";
export { identities } from "../api/entities/identities.ts";
export { type Project, projects } from "../api/entities/projects.ts";
export { type Session, sessions } from "../api/entities/sessions.ts";
export { type User, users } from "../api/entities/users.ts";
export {
  type DashboardCard,
  type DashboardCardInsert,
  dashboardCards,
} from "../api/entities/dashboardCards.ts";
export {
  type DashboardSettings,
  dashboardSettings,
} from "../api/entities/dashboardSettings.ts";
export {
  type NotificationPreferences,
  notificationPreferences,
} from "../api/entities/notificationPreferences.ts";
export {
  type ProjectCapability,
  projectCapabilities,
} from "../api/entities/projectCapabilities.ts";
export {
  type ProjectDashboardCard,
  type ProjectDashboardCardInsert,
  projectDashboardCards,
} from "../api/entities/projectDashboardCards.ts";
export {
  type ProjectPrompt,
  projectPrompts,
} from "../api/entities/projectPrompts.ts";
