/**
 * The browser-safe schemas of `@lore/core`, the glue: projects, capabilities, ranks and permissions, notifications, audits, the resource registry and its link graph, search, the dashboard, reports, agent prompts and the web shell.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export { CapabilityRegistry } from "../api/schemas/CapabilityRegistry.ts";
export { DashboardMetricCatalog } from "../api/schemas/DashboardMetricCatalog.ts";
export { ProjectSlugService } from "../api/schemas/ProjectSlugService.ts";
export { type AdminProjectResource } from "../api/schemas/adminProjectResourceSchema.ts";
export {
  type AgentPromptKind,
  agentPromptKindSchema,
} from "../api/schemas/agentPromptKindSchema.ts";
export {
  APP_NAME_MAX_LENGTH,
  APP_NAME_PATTERN,
  SIGIL_NAME_PAIR_MAX_LENGTH,
  appNameSchema,
} from "../api/schemas/appNameSchema.ts";
export {
  CAPABILITY_KEYS,
  type CapabilityKey,
} from "../api/schemas/capabilityKeySchema.ts";
export { type DashboardCardValue } from "../api/schemas/dashboardCardValueSchema.ts";
export { type DashboardScope } from "../api/schemas/dashboardScopeSchema.ts";
export { type KanbanColumnSettings } from "../api/schemas/kanbanColumnSchema.ts";
export {
  type LinkSourceKind,
  linkSourceKindSchema,
} from "../api/schemas/linkSourceKindSchema.ts";
export {
  type LinkTargetKind,
  linkTargetKindSchema,
} from "../api/schemas/linkTargetKindSchema.ts";
export {
  PALETTE_COLORS,
  type PaletteColor,
  paletteColorSchema,
} from "../api/schemas/paletteColorSchema.ts";
export {
  type ProjectResource,
  projectResourceSchema,
} from "../api/schemas/projectResourceSchema.ts";
export { projectTitleSchema } from "../api/schemas/projectTitleSchema.ts";
export {
  RELEASE_TAG_MAX_LENGTH,
  RELEASE_TAG_PATTERN,
  releaseTagSchema,
} from "../api/schemas/releaseTagSchema.ts";
export {
  reportsMembersSchema,
  reportsOverviewSchema,
  reportsQuestsSchema,
} from "../api/schemas/reportsSchemas.ts";
export { type RoadmapVisibility } from "../api/schemas/roadmapVisibilitySchema.ts";
export { attachmentPushResultSchema } from "../mcp/schemas/attachmentPushResultSchema.ts";
export { DIAGRAM_CAPABILITY } from "../mcp/schemas/diagramCapability.ts";
export { diagramWarningsShape } from "../mcp/schemas/diagramWarningsSchema.ts";
export { entityRefSchema } from "../mcp/schemas/entityRefSchema.ts";
export { epicStatusSchema } from "../mcp/schemas/epicStatusSchema.ts";
export { prioritySchema } from "../mcp/schemas/prioritySchema.ts";
export { projectParamsSchema } from "../mcp/schemas/projectParamsSchema.ts";
export { folioLinks } from "../api/entities/folioLinks.ts";
export { type Project, projects } from "../api/entities/projects.ts";
export { type User, users } from "../api/entities/users.ts";
export { dashboardCards } from "../api/entities/dashboardCards.ts";
export { dashboardSettings } from "../api/entities/dashboardSettings.ts";
export { notificationPreferences } from "../api/entities/notificationPreferences.ts";
export { projectCapabilities } from "../api/entities/projectCapabilities.ts";
export { projectDashboardCards } from "../api/entities/projectDashboardCards.ts";
