import { $module } from "alepha";
import { StreamableHttpMcpTransport } from "alepha/mcp";

import { McpCallRates } from "../api/services/McpCallRates.ts";
import { ProjectResources } from "./resources/ProjectResources.ts";
import { AttachmentContentService } from "./services/AttachmentContentService.ts";
import { AttachmentPushCommand } from "./services/AttachmentPushCommand.ts";
import { ProjectTools } from "./tools/ProjectTools.ts";

/**
 * The MCP tools and resources of `@lore/core`, the glue: projects, capabilities, ranks and permissions, notifications, audits, the resource registry and its link graph, search, the dashboard, reports, agent prompts and the web shell.
 *
 * Registered by `apps/lore/src/main.server.ts` beside `LoreCoreApi`.
 *
 * @module
 */
export const LoreCoreMcp = $module({
  name: "lore.core.mcp",
  services: [
    StreamableHttpMcpTransport,
    // Counts every tool call into the `mcp_calls` dataset (#E65). Listed
    // here because nothing injects it: it is a `$hook` subscriber and the
    // event reaches it only if the class was constructed.
    McpCallRates,
    ProjectTools,
    ProjectResources,
    AttachmentContentService,
    AttachmentPushCommand,
  ],
});

// ---- re-exports, generated by the extraction (#E75) ----

export { ProjectResources } from "./resources/ProjectResources.ts";
export { AttachmentContentService } from "./services/AttachmentContentService.ts";
export { AttachmentPushCommand } from "./services/AttachmentPushCommand.ts";
export { DiagramCheckService } from "./services/DiagramCheckService.ts";
export {
  type ProjectContextInput,
  ProjectContextRegistry,
  type ProjectContextSection,
} from "./services/ProjectContextRegistry.ts";
export { ProjectTools } from "./tools/ProjectTools.ts";
