import { LoreCoreWeb } from "@lore/core/web";
import { $module } from "alepha";

import { DeployDashboardMetrics } from "../api/services/DeployDashboardMetrics.ts";
import { DeployAccountRouter } from "./app/components/account/DeployAccountRouter.ts";
import { DeployRouter } from "./app/DeployRouter.ts";
import { DeployProjectLoader } from "./app/loaders/DeployProjectLoader.ts";
import { DeployShell } from "./app/shell/DeployShell.ts";

/**
 * The browser-safe half of `@lore/deploy`, Lore as Vercel: apps, telemetry (sigils, analytics, vitals, blights, quality), deployments and estates: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreDeployWeb = $module({
  name: "lore.deploy.web",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreWeb],
  register(alepha) {
    // Injected rather than listed in `services`: a listed service is tagged
    // with this module, and injecting it anywhere (a spec, a component
    // importing it from the barrel) would then register the whole module.
    //
    // The pages; Deploy's account page; its part of opening a project and
    // of the project shell, on core's registries, which nothing else would
    // construct; and its dashboard metrics' declarative half.
    alepha.inject(DeployRouter);
    alepha.inject(DeployAccountRouter);
    alepha.inject(DeployProjectLoader);
    alepha.inject(DeployShell);
    alepha.inject(DeployDashboardMetrics);
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { ANALYTICS_DIMENSIONS, DeployRouter } from "./app/DeployRouter.ts";
export { currentBlightCountAtom } from "./app/atoms/currentBlightCountAtom.ts";
export { currentEstateAtom } from "./app/atoms/currentEstateAtom.ts";
export { currentInstanceAtom } from "./app/atoms/currentInstanceAtom.ts";
export { currentInstancesAtom } from "./app/atoms/currentInstancesAtom.ts";
export { DeployAccountRouter } from "./app/components/account/DeployAccountRouter.ts";
export {
  default as MyEstateCreateDialog,
  type MyEstateCreateDialogProps,
} from "./app/components/account/MyEstateCreateDialog.tsx";
export {
  default as MyEstateDrawer,
  type MyEstateDrawerProps,
} from "./app/components/account/MyEstateDrawer.tsx";
export {
  default as MyEstateSecretDialog,
  type MyEstateSecretDialogProps,
} from "./app/components/account/MyEstateSecretDialog.tsx";
export { useOwnedEstatesDeletionLine } from "./app/components/account/useOwnedEstatesDeletionLine.ts";
export {
  default as BayActions,
  type BayActionsProps,
} from "./app/components/bay/BayActions.tsx";
export type { BayCommandsProps } from "./app/components/bay/BayCommands.tsx";
export {
  default as BayLogTail,
  type BayLogTailProps,
} from "./app/components/bay/BayLogTail.tsx";
export {
  default as BayStateBadge,
  type BayStateBadgeProps,
} from "./app/components/bay/BayStateBadge.tsx";
export { default as BayStatsChart } from "./app/components/bay/BayStatsChart.client.tsx";
export {
  default as BayUsageBar,
  type BayUsageBarProps,
} from "./app/components/bay/BayUsageBar.tsx";
export {
  type BayInstanceRow,
  type BayProcessState,
  bayInstanceRows,
  bayProcessState,
} from "./app/components/bay/bayInstanceRow.ts";
export {
  type BayCommandBody,
  useBayCommand,
} from "./app/components/bay/useBayCommand.ts";
export { useBayInventory } from "./app/components/bay/useBayInventory.ts";
export {
  default as AppAnalyticsEstimatedBadge,
  type AppAnalyticsEstimatedBadgeProps,
} from "./app/components/project/apps/AppAnalyticsEstimatedBadge.tsx";
export {
  default as AppAnalyticsFilterChips,
  type AppAnalyticsFilterChipsProps,
} from "./app/components/project/apps/AppAnalyticsFilterChips.tsx";
export {
  default as AppAnalyticsLeaderboard,
  type AppAnalyticsLeaderboardProps,
  type AppAnalyticsLeaderboardRow,
  type AppAnalyticsLeaderboardSegment,
} from "./app/components/project/apps/AppAnalyticsLeaderboard.tsx";
export {
  default as AppArtifactsList,
  type AppArtifactsListProps,
} from "./app/components/project/apps/AppArtifactsList.tsx";
export {
  default as AppArtifactsRow,
  type AppArtifactsRowProps,
} from "./app/components/project/apps/AppArtifactsRow.tsx";
export {
  default as AppCreateDialog,
  type AppCreateDialogProps,
} from "./app/components/project/apps/AppCreateDialog.tsx";
export {
  default as AppDashboardCapabilities,
  type AppDashboardCapabilitiesProps,
} from "./app/components/project/apps/AppDashboardCapabilities.tsx";
export {
  default as AppDashboardIdentity,
  type AppDashboardIdentityProps,
} from "./app/components/project/apps/AppDashboardIdentity.tsx";
export { default as AppDashboardNextSteps } from "./app/components/project/apps/AppDashboardNextSteps.tsx";
export {
  default as AppDeployRun,
  type AppDeployRunProps,
} from "./app/components/project/apps/AppDeployRun.tsx";
export {
  default as AppDeployRuns,
  type AppDeployRunsProps,
} from "./app/components/project/apps/AppDeployRuns.tsx";
export {
  default as AppEnvironmentAdd,
  type AppEnvironmentAddProps,
} from "./app/components/project/apps/AppEnvironmentAdd.tsx";
export {
  default as AppEnvironmentImport,
  type AppEnvironmentImportProps,
} from "./app/components/project/apps/AppEnvironmentImport.tsx";
export {
  default as AppErrorsStat,
  type AppErrorsStatProps,
} from "./app/components/project/apps/AppErrorsStat.tsx";
export {
  default as AppInsightsControls,
  type AppInsightsControlsProps,
} from "./app/components/project/apps/AppInsightsControls.tsx";
export { default as AppLayoutSwitcher } from "./app/components/project/apps/AppLayoutSwitcher.tsx";
export { default as AppSettingsDelete } from "./app/components/project/apps/AppSettingsDelete.tsx";
export { default as AppSettingsEstate } from "./app/components/project/apps/AppSettingsEstate.tsx";
export {
  default as AppSettingsRename,
  type AppSettingsRenameProps,
} from "./app/components/project/apps/AppSettingsRename.tsx";
export { default as AppSettingsSigil } from "./app/components/project/apps/AppSettingsSigil.tsx";
export { default as AppSettingsUrl } from "./app/components/project/apps/AppSettingsUrl.tsx";
export {
  default as AppStatusDot,
  type AppStatusDotProps,
} from "./app/components/project/apps/AppStatusDot.tsx";
export {
  default as AppVitalsCard,
  type AppVitalsCardProps,
  type VitalRating,
} from "./app/components/project/apps/AppVitalsCard.tsx";
export {
  default as AppVitalsDistribution,
  type AppVitalsDistributionProps,
} from "./app/components/project/apps/AppVitalsDistribution.tsx";
export { default as AppVitalsPaths } from "./app/components/project/apps/AppVitalsPaths.tsx";
export { appInsightsFiltersSchema } from "./app/components/project/apps/appInsightsFiltersSchema.ts";
export {
  type AppLiveness,
  appLiveness,
} from "./app/components/project/apps/appLiveness.ts";
export {
  APP_TABS,
  type AppTab,
  type AppTabLabelKey,
  type AppTabOption,
  type AppTabRoute,
  type GatedAppTab,
  type UngatedAppTab,
  appTabsFor,
  appTabsFrom,
} from "./app/components/project/apps/appTabs.ts";
export { appUrl, appUrlLabel } from "./app/components/project/apps/appUrl.ts";
export {
  VITAL_METRICS,
  vitalThresholds,
} from "./app/components/project/apps/appVitalMetrics.ts";
export {
  type AppEnvironmentActions,
  type AppEnvironmentItem,
  useAppEnvironmentActions,
} from "./app/components/project/apps/useAppEnvironmentActions.ts";
export {
  APP_INSIGHTS_FILTER_KEYS,
  APP_INSIGHTS_RANGES,
  APP_INSIGHTS_TRAFFICS,
  type AppInsightsFilterKey,
  type AppInsightsRange,
  type AppInsightsTraffic,
  useAppInsights,
  useAppInsightsFilters,
} from "./app/components/project/apps/useAppInsights.ts";
export { useDashboardApps } from "./app/components/project/apps/useDashboardApps.ts";
export type { ReleaseArtifactsPanelProps } from "./app/components/project/artifacts/ReleaseArtifactsPanel.tsx";
export {
  default as ReleaseArtifactsTab,
  type ReleaseArtifactsTabProps,
} from "./app/components/project/artifacts/ReleaseArtifactsTab.tsx";
export {
  type DeletableArtifact,
  type DeleteArtifact,
  useDeleteArtifact,
} from "./app/components/project/artifacts/useDeleteArtifact.ts";
export { useReleaseArtifacts } from "./app/components/project/artifacts/useReleaseArtifacts.ts";
export {
  default as BlightSourceCell,
  type BlightSourceCellProps,
} from "./app/components/project/blights/BlightSourceCell.tsx";
export {
  default as ProjectBlightRulesDialog,
  type ProjectBlightRulesDialogProps,
} from "./app/components/project/blights/ProjectBlightRulesDialog.tsx";
export { blightSourceHref } from "./app/components/project/blights/blightSourceHref.ts";
export { sigilNameParts } from "./app/components/project/blights/sigilNameParts.ts";
export type { ReportsQualityProps } from "./app/components/project/reports/ReportsQuality.client.tsx";
export {
  default as ReportsQualityEmpty,
  type ReportsQualityEmptyProps,
} from "./app/components/project/reports/ReportsQualityEmpty.tsx";
export {
  default as ReportsQualityStaleness,
  type ReportsQualityStalenessProps,
} from "./app/components/project/reports/ReportsQualityStaleness.tsx";
export {
  default as ProjectSettingsEstateRow,
  type ProjectSettingsEstateRowProps,
} from "./app/components/project/settings/ProjectSettingsEstateRow.tsx";
export {
  default as ProjectSettingsEstatesAddDialog,
  type ProjectSettingsEstatesAddDialogProps,
} from "./app/components/project/settings/ProjectSettingsEstatesAddDialog.tsx";
export {
  default as ArtifactPullCommand,
  type ArtifactPullCommandProps,
} from "./app/components/shared/ArtifactPullCommand.tsx";
export {
  default as ArtifactRuntimeBadges,
  type ArtifactRuntimeBadgesProps,
} from "./app/components/shared/ArtifactRuntimeBadges.tsx";
export {
  default as ArtifactsEmpty,
  type ArtifactsEmptyProps,
} from "./app/components/shared/ArtifactsEmpty.tsx";
export {
  default as EstateCreateFields,
  type EstateCreateFieldsProps,
} from "./app/components/shared/EstateCreateFields.tsx";
export {
  type EstateCreateDraft,
  emptyEstateDraft,
  estateDraftBody,
  estateDraftSlug,
  estateDraftValid,
  estateErrorField,
  estateErrorMessage,
} from "./app/components/shared/estateCreateDraft.ts";
export { estateCreateFormSchema } from "./app/components/shared/estateCreateFormSchema.ts";
export { DeployProjectLoader } from "./app/loaders/DeployProjectLoader.ts";
export { blightTriagePromptDefault } from "./app/prompts/blightTriagePrompt.ts";
export {
  type DotenvEntry,
  type DotenvError,
  type DotenvParseResult,
  DotenvParser,
} from "./app/services/DotenvParser.ts";
export { DeployShell } from "./app/shell/DeployShell.ts";
