import { LoreCoreWeb } from "@lore/core/web";
import { $module } from "alepha";

import { DeployDashboardMetrics } from "../api/services/DeployDashboardMetrics.ts";
import { DeployAccountRouter } from "./app/components/account/DeployAccountRouter.ts";
import { DeployRouter } from "./app/DeployRouter.ts";
import { DeployProjectLoader } from "./app/loaders/DeployProjectLoader.ts";
import { DeployShell } from "./app/shell/DeployShell.ts";

/**
 * The browser-safe half of `@lore/deploy`, Lore as Vercel: apps, telemetry (sigils, analytics, vitals, blights, quality), deployments and estates: its pages, atoms and
 * dictionaries.
 *
 * Registered by BOTH entries, `main.server.ts` and `main.browser.ts`: the
 * server renders and the browser hydrates from the same page registry, so a
 * page known to one side only renders on the server and 404s after hydration.
 *
 * It imports another package's `./api` or `./mcp` as `import type` only:
 * a runtime import would bundle that package's server into the browser.
 *
 * @module
 */
export const LoreDeployWeb = $module({
  name: "lore.deploy.web",
  // Core first: booting this module alone boots what it depends on.
  imports: [LoreCoreWeb],
  register(alepha) {
    // Injected rather than listed in `services`: a listed service is tagged
    // with this module, and injecting it anywhere (a spec, a component
    // importing it from the barrel) would then register the whole module.
    //
    // The pages; Deploy's account page; its part of opening a project and
    // of the project shell, on core's registries, which nothing else would
    // construct; and its dashboard metrics' declarative half.
    alepha.inject(DeployRouter);
    alepha.inject(DeployAccountRouter);
    alepha.inject(DeployProjectLoader);
    alepha.inject(DeployShell);
    alepha.inject(DeployDashboardMetrics);
  },
});

// ---- re-exports, generated by the extraction (#E75) ----

export { ANALYTICS_DIMENSIONS, DeployRouter } from "./app/DeployRouter.ts";
export { currentBlightCountAtom } from "./app/atoms/currentBlightCountAtom.ts";
export { currentInstancesAtom } from "./app/atoms/currentInstancesAtom.ts";
export { DeployAccountRouter } from "./app/components/account/DeployAccountRouter.ts";
export { DeployShell } from "./app/shell/DeployShell.ts";
