/**
 * The browser-safe schemas of `@lore/work`, Lore as Jira: quests, epics, releases, areas, the kanban, the roadmap and feedback.
 *
 * What another package, a browser page or an end-to-end spec may import as a
 * runtime value. Nothing here reaches a server-only module.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export { type Area, areas } from "../api/entities/areas.ts";
export { type Epic, epics } from "../api/entities/epics.ts";
export {
  type Feedback,
  type FeedbackInsert,
  feedback,
} from "../api/entities/feedback.ts";
export {
  type FeedbackComment,
  feedbackComments,
} from "../api/entities/feedbackComments.ts";
export {
  type QuestComment,
  questComments,
} from "../api/entities/questComments.ts";
export {
  type Quest,
  type QuestInsert,
  type QuestUpdate,
  REMINDER_INTERVAL_MS,
  REMINDER_INTERVAL_VALUES,
  type ReminderInterval,
  normalizeQuestTags,
  quests,
} from "../api/entities/quests.ts";
export { type Release, releases } from "../api/entities/releases.ts";
export {
  KanbanColumnConfig,
  type ResolvedKanbanColumn,
} from "../api/schemas/KanbanColumnConfig.ts";
export {
  type ActiveQuestsFilters,
  activeQuestsFiltersSchema,
} from "../api/schemas/activeQuestsFiltersSchema.ts";
export {
  type AreaDetail,
  type AreaResource,
  areaDetailSchema,
  areaResourceSchema,
} from "../api/schemas/areaResourceSchema.ts";
export { attachmentLookupSchema } from "../api/schemas/attachmentLookupSchema.ts";
export { epicCreateSchema } from "../api/schemas/epicCreateSchema.ts";
export { epicManualStatusSchema } from "../api/schemas/epicManualStatusSchema.ts";
export {
  type EpicProgressFilters,
  epicProgressFiltersSchema,
} from "../api/schemas/epicProgressFiltersSchema.ts";
export {
  type EpicRefResource,
  epicRefResourceSchema,
} from "../api/schemas/epicRefResourceSchema.ts";
export {
  type EpicResource,
  epicResourceSchema,
} from "../api/schemas/epicResourceSchema.ts";
export { feedbackBodySchema } from "../api/schemas/feedbackBodySchema.ts";
export {
  type FeedbackCommentResource,
  feedbackCommentResourceSchema,
} from "../api/schemas/feedbackCommentResourceSchema.ts";
export {
  type FeedbackLinkedQuest,
  type FeedbackResource,
  feedbackLinkedQuestSchema,
  feedbackResourceSchema,
} from "../api/schemas/feedbackResourceSchema.ts";
export {
  type FeedbackSource,
  feedbackSourceSchema,
} from "../api/schemas/feedbackSourceSchema.ts";
export {
  type HeldQuestsFilters,
  heldQuestsFiltersSchema,
} from "../api/schemas/heldQuestsFiltersSchema.ts";
export {
  type MemberRoadmapResource,
  memberRoadmapResourceSchema,
} from "../api/schemas/memberRoadmapResourceSchema.ts";
export {
  type MyFeedbackResource,
  myFeedbackResourceSchema,
} from "../api/schemas/myFeedbackResourceSchema.ts";
export {
  type QuestCommentResource,
  questCommentResourceSchema,
} from "../api/schemas/questCommentResourceSchema.ts";
export {
  type QuestCommentSource,
  questCommentSourceSchema,
} from "../api/schemas/questCommentSourceSchema.ts";
export {
  type QuestCommit,
  questCommitSchema,
} from "../api/schemas/questCommitSchema.ts";
export { questCreateSchema } from "../api/schemas/questCreateSchema.ts";
export {
  MAX_QUEST_OBJECTIVES,
  exceedsObjectiveCap,
  objectiveCapMessage,
} from "../api/schemas/questObjectivesLimit.ts";
export {
  QUEST_PRIORITY_ORDER,
  type QuestPriority,
  byPriorityDesc,
} from "../api/schemas/questPriority.ts";
export { QUEST_RELEASE_NONE } from "../api/schemas/questReleaseFilter.ts";
export {
  type QuestResource,
  type QuestStatus,
  questResourceSchema,
  questStatusSchema,
} from "../api/schemas/questResourceSchema.ts";
export {
  type QuestSource,
  questSourceSchema,
} from "../api/schemas/questSourceSchema.ts";
export {
  type ReleaseCascade,
  releaseCascadeSchema,
} from "../api/schemas/releaseCascadeSchema.ts";
export {
  type ReleaseChangelogGroup,
  releaseChangelogGroupSchema,
} from "../api/schemas/releaseChangelogGroupSchema.ts";
export {
  type ReleaseContentQuest,
  releaseContentQuestSchema,
} from "../api/schemas/releaseContentQuestSchema.ts";
export {
  type ReleaseProgressFilters,
  releaseProgressFiltersSchema,
} from "../api/schemas/releaseProgressFiltersSchema.ts";
export {
  type ReleaseResource,
  releaseResourceSchema,
} from "../api/schemas/releaseResourceSchema.ts";
export {
  type RoadmapEpic,
  roadmapEpicSchema,
} from "../api/schemas/roadmapEpicSchema.ts";
export {
  type RoadmapRelease,
  roadmapReleaseSchema,
} from "../api/schemas/roadmapReleaseSchema.ts";
export {
  type RoadmapResource,
  roadmapResourceSchema,
} from "../api/schemas/roadmapResourceSchema.ts";
export {
  type SupportCapabilityOptions,
  supportCapabilityOptionsSchema,
} from "../api/schemas/supportCapabilityOptionsSchema.ts";
export {
  type TagCompletionFilters,
  tagCompletionFiltersSchema,
} from "../api/schemas/tagCompletionFiltersSchema.ts";
export {
  type UntriagedFeedbackFilters,
  untriagedFeedbackFiltersSchema,
} from "../api/schemas/untriagedFeedbackFiltersSchema.ts";
export {
  type WorkCapabilityOptions,
  workCapabilityOptionsSchema,
} from "../api/schemas/workCapabilityOptionsSchema.ts";
export {
  epicCreateParamsSchema,
  epicCreateResultSchema,
  epicDeleteParamsSchema,
  epicDeleteResultSchema,
  epicGetParamsSchema,
  epicGetResultSchema,
  epicListParamsSchema,
  epicListResultSchema,
  epicSetStatusParamsSchema,
  epicSetStatusResultSchema,
  epicUpdateParamsSchema,
  epicUpdateResultSchema,
} from "../mcp/schemas/epicSchemas.ts";
export {
  feedbackAttachmentGetParamsSchema,
  feedbackCommentAddParamsSchema,
  feedbackCommentAddResultSchema,
  feedbackGetParamsSchema,
  feedbackGetResultSchema,
  feedbackListParamsSchema,
  feedbackListResultSchema,
  feedbackTriageParamsSchema,
  feedbackTriageResultSchema,
} from "../mcp/schemas/feedbackSchemas.ts";
export { objectiveInputSchema } from "../mcp/schemas/objectiveInputSchema.ts";
export { objectiveSchema } from "../mcp/schemas/objectiveSchema.ts";
export {
  questAcceptParamsSchema,
  questAcceptResultSchema,
  questAttachmentAddParamsSchema,
  questAttachmentAddResultSchema,
  questAttachmentGetParamsSchema,
  questCommentAddParamsSchema,
  questCommentAddResultSchema,
  questCommitAddParamsSchema,
  questCommitAddResultSchema,
  questCompleteParamsSchema,
  questCompleteResultSchema,
  questCreateParamsSchema,
  questCreateResultSchema,
  questDeleteParamsSchema,
  questDeleteResultSchema,
  questGetParamsSchema,
  questGetResultSchema,
  questHoldParamsSchema,
  questHoldResultSchema,
  questListParamsSchema,
  questListResultSchema,
  questObjectiveSetParamsSchema,
  questObjectiveSetResultSchema,
  questShelveParamsSchema,
  questShelveResultSchema,
  questTagsParamsSchema,
  questTagsResultSchema,
  questUnassignParamsSchema,
  questUnassignResultSchema,
  questUnholdParamsSchema,
  questUnholdResultSchema,
  questUnshelveParamsSchema,
  questUnshelveResultSchema,
  questUpdateParamsSchema,
  questUpdateResultSchema,
} from "../mcp/schemas/questSchemas.ts";
export { questSizeSchema } from "../mcp/schemas/questSizeSchema.ts";
export {
  releaseAttachParamsSchema,
  releaseAttachResultSchema,
  releaseChangelogParamsSchema,
  releaseChangelogResultSchema,
  releaseCreateParamsSchema,
  releaseCreateResultSchema,
  releaseDeleteParamsSchema,
  releaseDeleteResultSchema,
  releaseDetachParamsSchema,
  releaseDetachResultSchema,
  releaseGetParamsSchema,
  releaseGetResultSchema,
  releaseListParamsSchema,
  releaseListResultSchema,
  releasePublishParamsSchema,
  releasePublishResultSchema,
  releaseReopenParamsSchema,
  releaseReopenResultSchema,
  releaseSetDefaultParamsSchema,
  releaseSetDefaultResultSchema,
  releaseUpdateParamsSchema,
  releaseUpdateResultSchema,
} from "../mcp/schemas/releaseSchemas.ts";

// Browser-loadable although it sits in `api/services`: the dashboard's
// declarative half, read by the catalogue on both sides.
export { WorkDashboardMetrics } from "../api/services/WorkDashboardMetrics.ts";

// Pure, and read by the browser and the e2e suite alike.
export {
  type ReleaseTagParts,
  compareReleaseTags,
  parseReleaseTag,
} from "../api/releaseOrder.ts";
