import { LoreCoreMcp } from "@lore/core/mcp";
import { $module } from "alepha";

import { AppInstanceTools } from "./tools/AppInstanceTools.ts";
import { ArtifactTools } from "./tools/ArtifactTools.ts";
import { BlightTools } from "./tools/BlightTools.ts";
import { DeployTools } from "./tools/DeployTools.ts";
import { InsightsTools } from "./tools/InsightsTools.ts";
import { SigilTools } from "./tools/SigilTools.ts";

/**
 * The MCP tools and resources of `@lore/deploy`, Lore as Vercel: apps, telemetry (sigils, analytics, vitals, blights, quality), deployments and estates.
 *
 * Registered by `apps/lore/src/main.server.ts` beside `LoreDeployApi`.
 *
 * @module
 */
export const LoreDeployMcp = $module({
  name: "lore.deploy.mcp",
  imports: [LoreCoreMcp],
  services: [
    BlightTools,
    ArtifactTools,
    AppInstanceTools,
    DeployTools,
    SigilTools,
    InsightsTools,
  ],
});

// ---- re-exports, generated by the extraction (#E75) ----

export { AppInstanceTools } from "./tools/AppInstanceTools.ts";
export { ArtifactTools } from "./tools/ArtifactTools.ts";
export { BlightTools } from "./tools/BlightTools.ts";
export { DeployTools } from "./tools/DeployTools.ts";
export { InsightsTools } from "./tools/InsightsTools.ts";
export { SigilTools } from "./tools/SigilTools.ts";
