/**
 * The fixtures every `@lore` package's specs boot with: the project fixture
 * and the entity bag.
 *
 * Specs only. Nothing under `src/api`, `src/mcp` or `src/web` imports it.
 *
 * @module
 */

// ---- re-exports, generated by the extraction (#E75) ----

export {
  type ProjectFixtureOptions,
  projectFixture,
} from "./projectFixture.ts";
export { virtualClientFake } from "./virtualClientFake.ts";

// ---- what specs render or read that the runtime barrels must not name ----
//
// The pages below are loaded by a route, and the catalogs by `$dictionary`'s
// `lazy`: a static re-export from `./web` would hoist them into the static
// graph (#Q2425, #E75). Nothing at runtime imports `./testing`.
export { default as en } from "../web/locales/en.ts";
export { default as fr } from "../web/locales/fr.ts";
export { default as ProjectSettingsAgentPrompts } from "../web/app/components/project/settings/ProjectSettingsAgentPrompts.tsx";
export { default as ProjectSettingsCapabilitiesPage } from "../web/app/components/project/settings/ProjectSettingsCapabilitiesPage.tsx";
export { default as ProjectSettingsRanksPage } from "../web/app/components/project/settings/ProjectSettingsRanksPage.tsx";
