import { $inject, AlephaError } from "alepha";
import {
  HeadersFileReader,
  type HeadersProblem,
  type HeadersRule,
} from "alepha/server/static";
import { FileSystemProvider } from "alepha/system";

import { BuildClientTask } from "./BuildClientTask.ts";
import { BuildTask, type BuildTaskContext } from "./BuildTask.ts";

/**
 * Write `dist/public/_headers`: the app's headers, for every host that serves
 * its files without passing them through the app.
 *
 * A host that answers a file itself never runs the app's code, so the headers
 * the app would have sent never reach that file: Cloudflare's asset store, Bay
 * serving `dist/public` from disk. One file in Cloudflare's format carries them
 * instead, and every host applies it: Cloudflare through both deploy paths,
 * Bay, and the app's own static server, on disk or embedded in a binary.
 *
 * ## The layout
 *
 * 1. `/*` with the security headers `helmetOptions` produces, then the
 *    author's own `/*` lines folded in.
 * 2. The rest of the author's `public/_headers`, verbatim.
 * 3. `/entry.*`, `/chunk.*` and `/asset.*`, each removing `Cache-Control`
 *    before setting a year immutable, so they win over any broad author rule:
 *    a content-addressed name never changes meaning. Not for a
 *    `static.source` build, whose names Alepha never chose.
 *
 * ## Where the author's file comes from
 *
 * From `dist/public/_headers` itself, as Vite or `static.source` left it.
 * `BuildCommand` removes `dist/` before any task runs, so that file can only be
 * the author's copy, and reading it there honours an app-configured Vite
 * `publicDir` and an adopted static site with no extra plumbing.
 *
 * Runs after `BuildStaticTask`, which copies an adopted site in, and before
 * `BuildCompressTask` and `BuildCompileTask`: the binary embeds `dist/public`
 * and the directory is deleted.
 */
export class BuildHeadersTask extends BuildTask {
  /**
   * The first line of every file this task writes. A `dist/public/_headers`
   * already starting with it means `dist/` was not cleaned, and merging a
   * generated file into itself would duplicate every rule.
   */
  public static readonly GENERATED =
    "# Generated by `alepha build`. Edit public/_headers or helmetOptions, never this file.";

  protected static readonly IMMUTABLE = "public, max-age=31536000, immutable";

  protected readonly fs = $inject(FileSystemProvider);
  protected readonly reader = $inject(HeadersFileReader);
  protected readonly clientTask = $inject(BuildClientTask);

  async run(ctx: BuildTaskContext): Promise<void> {
    if (ctx.flags?.prebuilt) {
      return;
    }
    const dist = ctx.options.output?.dist ?? "dist";
    const pub = ctx.options.output?.public ?? "public";
    const dir = this.fs.join(ctx.root, dist, pub);
    if (!(await this.fs.exists(dir))) {
      return;
    }

    await ctx.run({
      name: "write _headers",
      handler: async () => {
        await this.write(ctx, dir);
      },
    });
  }

  /**
   * Merge, validate, then write `<dir>/_headers`.
   *
   * @throws {AlephaError} naming every problem at the author's line numbers.
   */
  protected async write(ctx: BuildTaskContext, dir: string): Promise<void> {
    const path = this.fs.join(dir, "_headers");
    const author = (await this.fs.exists(path))
      ? await this.fs.readTextFile(path)
      : "";
    const adopted = ctx.options.static?.source;
    const source = adopted
      ? `${adopted.replace(/\/+$/, "")}/_headers`
      : "public/_headers";

    if (author.startsWith(BuildHeadersTask.GENERATED)) {
      throw new AlephaError(
        `${path} was already written by \`alepha build\`, so dist/ was not cleaned before this build. Remove dist/ and build again.`,
      );
    }

    // A site built by something else never promised Alepha's names, so
    // neither the hash rules nor the names they reserve apply to it.
    if (!adopted) {
      await this.refuseReservedNames();
    }

    const parsed = this.reader.parse(author);
    const problems: HeadersProblem[] = [...parsed.problems];

    const hashRules = adopted ? [] : this.hashRules();
    const generatedPaths = new Set(hashRules.map((it) => it.path));
    const authorRoot = parsed.rules.find((it) => it.path === "/*");
    const others: HeadersRule[] = [];
    for (const rule of parsed.rules) {
      if (rule === authorRoot) {
        continue;
      }
      if (generatedPaths.has(rule.path)) {
        problems.push({
          reason: "duplicate-path",
          lines: rule.line === undefined ? [] : [rule.line],
          message: `\`${rule.path}\` is written by the build, which caches every content-hashed file for a year. Remove this rule.`,
        });
        continue;
      }
      others.push(rule);
    }

    const security = this.securityHeaders(ctx);
    const root = this.fold(security, authorRoot, problems);
    const rules = [...(root ? [root] : []), ...others, ...hashRules];
    problems.push(...this.reader.validate(rules));

    if (problems.length > 0) {
      throw new AlephaError(this.reader.describe(problems, source));
    }
    if (rules.length === 0) {
      return;
    }

    await this.fs.writeFile(
      path,
      this.format(security, authorRoot, author, hashRules),
    );
  }

  /**
   * The headers `ServerHelmetProvider` adds to every response of the app, or
   * none when the app runs without it or turned it off.
   *
   * Asked for by name, the way `BuildManifestTask` asks for providers: the CLI
   * and the app are two module graphs, so a class imported here would never be
   * the one the app registered.
   *
   * @throws {AlephaError} when a value would not fit on one line of the file.
   */
  protected securityHeaders(ctx: BuildTaskContext): Record<string, string> {
    let helmet: { getHeaders?: () => Record<string, string> } | undefined;
    try {
      helmet = ctx.alepha.inject("ServerHelmetProvider") as typeof helmet;
    } catch {
      return {};
    }
    const headers = helmet?.getHeaders?.() ?? {};
    for (const [name, value] of Object.entries(headers)) {
      const line = `${this.headerCase(name)}: ${value}`;
      if (line.length > HeadersFileReader.MAX_LINE_LENGTH) {
        throw new AlephaError(
          `helmetOptions produces a ${name} of ${line.length} characters, and one line of _headers holds at most ${HeadersFileReader.MAX_LINE_LENGTH}: Cloudflare would skip it. Shorten the policy.`,
        );
      }
    }
    return headers;
  }

  /**
   * The one `/*` rule: the generated headers, then the author's.
   *
   * ⚠️ Cloudflare applies a rule's removals before its sets, so an author's
   * `! Name` inside the same rule as a generated `Name: value` would remove
   * nothing. The generated line for every header the author removes is
   * dropped here, and the author's `! Name` is kept: on the app's own server
   * it is what removes helmet's value.
   */
  protected fold(
    security: Record<string, string>,
    author: HeadersRule | undefined,
    problems: HeadersProblem[],
  ): HeadersRule | undefined {
    const generated = this.generatedRoot(security, author);
    if (generated.length === 0 && !author) {
      return undefined;
    }

    const removed = this.removedNames(author);
    const names = new Set(Object.keys(security).map((it) => it.toLowerCase()));
    for (const set of author?.set ?? []) {
      const lower = set.name.toLowerCase();
      if (names.has(lower) && !removed.has(lower)) {
        problems.push({
          reason: "silent-join",
          lines: set.line === undefined ? [] : [set.line],
          message: `\`/*\` sets \`${set.name}\`, which the build already sets there from helmetOptions, and the two values would be joined. Write \`! ${set.name}\` in the same rule to replace the generated one.`,
        });
      }
    }

    return {
      path: "/*",
      line: author?.line,
      unset: author?.unset ?? [],
      set: [...generated, ...(author?.set ?? [])],
    };
  }

  /**
   * The generated lines of `/*`, less every header the author's `/*` removes.
   */
  protected generatedRoot(
    security: Record<string, string>,
    author: HeadersRule | undefined,
  ): Array<{ name: string; value: string }> {
    const removed = this.removedNames(author);
    return Object.entries(security)
      .filter(([name]) => !removed.has(name.toLowerCase()))
      .map(([name, value]) => ({ name: this.headerCase(name), value }));
  }

  protected removedNames(author: HeadersRule | undefined): Set<string> {
    return new Set((author?.unset ?? []).map((it) => it.name.toLowerCase()));
  }

  /**
   * `/entry.*`, `/chunk.*` and `/asset.*`, from the names `BuildClientTask`
   * gives Vite, so a rename there cannot leave these pointing at nothing.
   */
  protected hashRules(): HeadersRule[] {
    return Object.values(BuildClientTask.HASHED_PREFIXES).map((prefix) => ({
      path: `/${prefix}*`,
      unset: [{ name: "Cache-Control" }],
      set: [{ name: "Cache-Control", value: BuildHeadersTask.IMMUTABLE }],
    }));
  }

  /**
   * Refuse a top-level file of the app's public directory named like a
   * content-hashed one.
   *
   * It would be cached for a year under a name the author can overwrite, and
   * a year on a mutable name is the one caching mistake no later deploy can
   * undo. Only the top level: `/asset.*` matches root-level names alone.
   */
  protected async refuseReservedNames(): Promise<void> {
    const publicDir = this.clientTask.getPublicDir();
    if (!publicDir || !(await this.fs.exists(publicDir))) {
      return;
    }
    const prefixes = Object.values(BuildClientTask.HASHED_PREFIXES);
    const reserved = (await this.fs.ls(publicDir)).filter((name) =>
      prefixes.some((prefix) => name.startsWith(prefix)),
    );
    if (reserved.length > 0) {
      throw new AlephaError(
        `${publicDir} holds ${reserved.map((it) => `\`${it}\``).join(", ")}, named like a content-hashed build file (${prefixes.map((it) => `${it}*`).join(", ")}). Those names are cached for a year as immutable, so a later change to the file would never reach a browser that has it. Rename it.`,
      );
    }
  }

  /**
   * The merged file, as text.
   */
  protected format(
    security: Record<string, string>,
    authorRoot: HeadersRule | undefined,
    author: string,
    hashRules: HeadersRule[],
  ): string {
    const blocks: string[] = [BuildHeadersTask.GENERATED];

    const generated = this.generatedRoot(security, authorRoot).map(
      (it) => `${it.name}: ${it.value}`,
    );
    // The author's `/*` lines, in the order they were written.
    const folded = authorRoot
      ? [
          ...authorRoot.unset.map((it) => ({
            line: it.line ?? 0,
            text: `! ${it.name}`,
          })),
          ...authorRoot.set.map((it) => ({
            line: it.line ?? 0,
            text: `${it.name}: ${it.value}`,
          })),
        ]
          .sort((a, b) => a.line - b.line)
          .map((it) => it.text)
      : [];
    if (generated.length > 0 || folded.length > 0) {
      blocks.push(
        ["/*", ...[...generated, ...folded].map((it) => `  ${it}`)].join("\n"),
      );
    }

    const rest = this.withoutRule(author, authorRoot).trim();
    if (rest !== "") {
      blocks.push(rest);
    }

    for (const rule of hashRules) {
      blocks.push(
        [
          rule.path,
          ...rule.unset.map((it) => `  ! ${it.name}`),
          ...rule.set.map((it) => `  ${it.name}: ${it.value}`),
        ].join("\n"),
      );
    }

    return `${blocks.join("\n\n")}\n`;
  }

  /**
   * The author's text without the lines of one rule, and everything else as
   * written: comments, blank lines, the other rules.
   */
  protected withoutRule(text: string, rule: HeadersRule | undefined): string {
    if (!rule) {
      return text;
    }
    const drop = new Set(
      [
        rule.line,
        ...rule.unset.map((it) => it.line),
        ...rule.set.map((it) => it.line),
      ].filter((it) => it !== undefined),
    );
    return text
      .split("\n")
      .filter((_, index) => !drop.has(index + 1))
      .join("\n");
  }

  /**
   * `strict-transport-security` as `Strict-Transport-Security`, for a person
   * reading the file. Names compare case-insensitively, so nothing else
   * changes.
   */
  protected headerCase(name: string): string {
    return name
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("-");
  }
}
