/**
 * The primitives every Alepha interface is built from.
 *
 * Buttons, inputs, cards, dialogs, sheets, menus, tooltips, the sidebar and the
 * rest of the Base UI + Tailwind primitives, each file exporting its whole
 * family. Beside them, the small pieces every surface reaches for: `cn` for
 * class merging, `useToast` with its `Toaster`, `useDialog` with its
 * `DialogProvider`, `useIsMobile`, `TimeAgo`, `UserAvatar`, `BrandIcon`,
 * `FileImage`, `PaneRail`, `FilterSlot`, and `Highlight` to mark what a
 * search matched in a text.
 *
 * Imports nothing from another `@alepha/ui` module, so
 * `import { Button } from "@alepha/ui"` never pulls in a form, a table or a
 * shell. Load the stylesheet once, at the app's entry: `@alepha/ui/styles.css`.
 *
 * @module alepha.ui
 */

export {
  Alert,
  type AlertProps,
  AlertAction,
  type AlertActionProps,
  AlertDescription,
  type AlertDescriptionProps,
  AlertTitle,
  type AlertTitleProps,
} from "./Alert.tsx";
export {
  AlertDialog,
  type AlertDialogProps,
  AlertDialogAction,
  type AlertDialogActionProps,
  AlertDialogCancel,
  type AlertDialogCancelProps,
  AlertDialogContent,
  type AlertDialogContentProps,
  AlertDialogDescription,
  type AlertDialogDescriptionProps,
  AlertDialogFooter,
  type AlertDialogFooterProps,
  AlertDialogHeader,
  type AlertDialogHeaderProps,
  AlertDialogMedia,
  type AlertDialogMediaProps,
  AlertDialogOverlay,
  type AlertDialogOverlayProps,
  AlertDialogPortal,
  type AlertDialogPortalProps,
  AlertDialogTitle,
  type AlertDialogTitleProps,
  AlertDialogTrigger,
  type AlertDialogTriggerProps,
} from "./AlertDialog.tsx";
export {
  Avatar,
  type AvatarProps,
  AvatarBadge,
  type AvatarBadgeProps,
  AvatarFallback,
  type AvatarFallbackProps,
  AvatarGroup,
  type AvatarGroupProps,
  AvatarGroupCount,
  type AvatarGroupCountProps,
  AvatarImage,
  type AvatarImageProps,
} from "./Avatar.tsx";
export {
  Badge,
  type BadgeProps,
  type BadgeTone,
  badgeVariants,
} from "./Badge.tsx";
export { BrandIcon, type BrandIconProps } from "./BrandIcon.tsx";
export {
  Breadcrumb,
  type BreadcrumbProps,
  BreadcrumbEllipsis,
  type BreadcrumbEllipsisProps,
  BreadcrumbItem,
  type BreadcrumbItemProps,
  BreadcrumbLink,
  type BreadcrumbLinkProps,
  BreadcrumbList,
  type BreadcrumbListProps,
  BreadcrumbPage,
  type BreadcrumbPageProps,
  BreadcrumbSeparator,
  type BreadcrumbSeparatorProps,
} from "./Breadcrumb.tsx";
export {
  Button,
  type ButtonIntent,
  type ButtonProps,
  type ButtonVariant,
  buttonVariants,
} from "./Button.tsx";
export {
  ButtonGroup,
  type ButtonGroupProps,
  ButtonGroupSeparator,
  type ButtonGroupSeparatorProps,
  ButtonGroupText,
  type ButtonGroupTextProps,
  buttonGroupVariants,
} from "./ButtonGroup.tsx";
export {
  Card,
  type CardProps,
  CardAction,
  type CardActionProps,
  CardContent,
  type CardContentProps,
  CardDescription,
  type CardDescriptionProps,
  CardFooter,
  type CardFooterProps,
  CardHeader,
  type CardHeaderProps,
  CardTitle,
  type CardTitleProps,
} from "./Card.tsx";
export { Checkbox, type CheckboxProps } from "./Checkbox.tsx";
export {
  Combobox,
  ComboboxChip,
  type ComboboxChipProps,
  ComboboxChips,
  type ComboboxChipsProps,
  ComboboxChipsInput,
  type ComboboxChipsInputProps,
  ComboboxCollection,
  type ComboboxCollectionProps,
  ComboboxContent,
  type ComboboxContentProps,
  ComboboxEmpty,
  type ComboboxEmptyProps,
  ComboboxGroup,
  type ComboboxGroupProps,
  ComboboxInput,
  type ComboboxInputProps,
  ComboboxItem,
  type ComboboxItemProps,
  ComboboxLabel,
  type ComboboxLabelProps,
  ComboboxList,
  type ComboboxListProps,
  ComboboxSeparator,
  type ComboboxSeparatorProps,
  ComboboxTrigger,
  type ComboboxTriggerProps,
  ComboboxValue,
  type ComboboxValueProps,
  useComboboxAnchor,
} from "./Combobox.tsx";
export {
  ContextMenu,
  type ContextMenuProps,
  ContextMenuCheckboxItem,
  type ContextMenuCheckboxItemProps,
  ContextMenuContent,
  type ContextMenuContentProps,
  ContextMenuGroup,
  type ContextMenuGroupProps,
  ContextMenuItem,
  type ContextMenuItemProps,
  ContextMenuLabel,
  type ContextMenuLabelProps,
  ContextMenuPortal,
  type ContextMenuPortalProps,
  ContextMenuRadioGroup,
  type ContextMenuRadioGroupProps,
  ContextMenuRadioItem,
  type ContextMenuRadioItemProps,
  ContextMenuSeparator,
  type ContextMenuSeparatorProps,
  ContextMenuShortcut,
  type ContextMenuShortcutProps,
  ContextMenuSub,
  type ContextMenuSubProps,
  ContextMenuSubContent,
  type ContextMenuSubContentProps,
  ContextMenuSubTrigger,
  type ContextMenuSubTriggerProps,
  ContextMenuTrigger,
  type ContextMenuTriggerProps,
} from "./ContextMenu.tsx";
export {
  Dialog,
  type DialogProps,
  DialogClose,
  type DialogCloseProps,
  DialogContent,
  type DialogContentProps,
  DialogDescription,
  type DialogDescriptionProps,
  DialogFooter,
  type DialogFooterProps,
  DialogHeader,
  type DialogHeaderProps,
  DialogOverlay,
  type DialogOverlayProps,
  DialogPortal,
  type DialogPortalProps,
  DialogTitle,
  type DialogTitleProps,
  DialogTrigger,
  type DialogTriggerProps,
} from "./Dialog.tsx";
export {
  Drawer,
  type DrawerProps,
  DrawerClose,
  type DrawerCloseProps,
  DrawerContent,
  type DrawerContentProps,
  DrawerDescription,
  type DrawerDescriptionProps,
  DrawerFooter,
  type DrawerFooterProps,
  DrawerHeader,
  type DrawerHeaderProps,
  DrawerOverlay,
  type DrawerOverlayProps,
  DrawerPortal,
  type DrawerPortalProps,
  DrawerSwipeHandle,
  type DrawerSwipeHandleProps,
  DrawerTitle,
  type DrawerTitleProps,
  DrawerTrigger,
  type DrawerTriggerProps,
} from "./Drawer.tsx";
export {
  DropdownMenu,
  type DropdownMenuProps,
  DropdownMenuCheckboxItem,
  type DropdownMenuCheckboxItemProps,
  DropdownMenuContent,
  type DropdownMenuContentProps,
  DropdownMenuGroup,
  type DropdownMenuGroupProps,
  DropdownMenuItem,
  type DropdownMenuItemProps,
  DropdownMenuLabel,
  type DropdownMenuLabelProps,
  DropdownMenuPortal,
  type DropdownMenuPortalProps,
  DropdownMenuRadioGroup,
  type DropdownMenuRadioGroupProps,
  DropdownMenuRadioItem,
  type DropdownMenuRadioItemProps,
  DropdownMenuSeparator,
  type DropdownMenuSeparatorProps,
  DropdownMenuShortcut,
  type DropdownMenuShortcutProps,
  DropdownMenuSub,
  type DropdownMenuSubProps,
  DropdownMenuSubContent,
  type DropdownMenuSubContentProps,
  DropdownMenuSubTrigger,
  type DropdownMenuSubTriggerProps,
  DropdownMenuTrigger,
  type DropdownMenuTriggerProps,
} from "./DropdownMenu.tsx";
export {
  Empty,
  type EmptyProps,
  EmptyContent,
  type EmptyContentProps,
  EmptyDescription,
  type EmptyDescriptionProps,
  EmptyHeader,
  type EmptyHeaderProps,
  EmptyMedia,
  type EmptyMediaProps,
  EmptyTitle,
  type EmptyTitleProps,
} from "./Empty.tsx";
export { FileImage, type FileImageProps } from "./FileImage.tsx";
export { FilterSlot, type FilterSlotProps } from "./FilterSlot.tsx";
export { Highlight, type HighlightProps } from "./Highlight.tsx";
export { highlightRanges } from "./highlightRanges.ts";
export {
  HoverCard,
  type HoverCardProps,
  HoverCardContent,
  type HoverCardContentProps,
  HoverCardTrigger,
  type HoverCardTriggerProps,
} from "./HoverCard.tsx";
export { Input, type InputProps } from "./Input.tsx";
export {
  InputGroup,
  type InputGroupProps,
  InputGroupAddon,
  type InputGroupAddonProps,
  InputGroupButton,
  type InputGroupButtonProps,
  InputGroupInput,
  type InputGroupInputProps,
  InputGroupText,
  type InputGroupTextProps,
  InputGroupTextarea,
  type InputGroupTextareaProps,
} from "./InputGroup.tsx";
export { Kbd, type KbdProps, KbdGroup, type KbdGroupProps } from "./Kbd.tsx";
export { Label, type LabelProps } from "./Label.tsx";
export {
  Menubar,
  type MenubarProps,
  MenubarCheckboxItem,
  type MenubarCheckboxItemProps,
  MenubarContent,
  type MenubarContentProps,
  MenubarGroup,
  type MenubarGroupProps,
  MenubarItem,
  type MenubarItemProps,
  MenubarLabel,
  type MenubarLabelProps,
  MenubarMenu,
  type MenubarMenuProps,
  MenubarPortal,
  type MenubarPortalProps,
  MenubarRadioGroup,
  type MenubarRadioGroupProps,
  MenubarRadioItem,
  type MenubarRadioItemProps,
  MenubarSeparator,
  type MenubarSeparatorProps,
  MenubarShortcut,
  type MenubarShortcutProps,
  MenubarSub,
  type MenubarSubProps,
  MenubarSubContent,
  type MenubarSubContentProps,
  MenubarSubTrigger,
  type MenubarSubTriggerProps,
  MenubarTrigger,
  type MenubarTriggerProps,
} from "./Menubar.tsx";
export {
  Pagination,
  type PaginationProps,
  PaginationContent,
  type PaginationContentProps,
  PaginationEllipsis,
  type PaginationEllipsisProps,
  PaginationItem,
  type PaginationItemProps,
  PaginationLink,
  type PaginationLinkProps,
  PaginationNext,
  type PaginationNextProps,
  PaginationPrevious,
  type PaginationPreviousProps,
} from "./Pagination.tsx";
export { PaneRail, type PaneRailProps } from "./PaneRail.tsx";
export {
  Popover,
  type PopoverProps,
  PopoverContent,
  type PopoverContentProps,
  PopoverDescription,
  type PopoverDescriptionProps,
  PopoverHeader,
  type PopoverHeaderProps,
  PopoverTitle,
  type PopoverTitleProps,
  PopoverTrigger,
  type PopoverTriggerProps,
} from "./Popover.tsx";
export {
  Progress,
  type ProgressProps,
  ProgressIndicator,
  type ProgressIndicatorProps,
  ProgressLabel,
  type ProgressLabelProps,
  ProgressTrack,
  type ProgressTrackProps,
  ProgressValue,
  type ProgressValueProps,
} from "./Progress.tsx";
export {
  Segmented,
  type SegmentedOption,
  type SegmentedProps,
} from "./Segmented.tsx";
export { Separator, type SeparatorProps } from "./Separator.tsx";
export {
  Sheet,
  type SheetProps,
  SheetClose,
  type SheetCloseProps,
  SheetContent,
  type SheetContentProps,
  SheetDescription,
  type SheetDescriptionProps,
  SheetFooter,
  type SheetFooterProps,
  SheetHeader,
  type SheetHeaderProps,
  SheetTitle,
  type SheetTitleProps,
  SheetTrigger,
  type SheetTriggerProps,
} from "./Sheet.tsx";
export {
  Sidebar,
  type SidebarProps,
  SidebarContent,
  type SidebarContentProps,
  SidebarFooter,
  type SidebarFooterProps,
  SidebarGroup,
  type SidebarGroupProps,
  SidebarGroupAction,
  type SidebarGroupActionProps,
  SidebarGroupContent,
  type SidebarGroupContentProps,
  SidebarGroupLabel,
  type SidebarGroupLabelProps,
  SidebarHeader,
  type SidebarHeaderProps,
  SidebarInput,
  type SidebarInputProps,
  SidebarInset,
  type SidebarInsetProps,
  SidebarMenu,
  type SidebarMenuProps,
  SidebarMenuAction,
  type SidebarMenuActionProps,
  SidebarMenuBadge,
  type SidebarMenuBadgeProps,
  SidebarMenuButton,
  type SidebarMenuButtonProps,
  SidebarMenuItem,
  type SidebarMenuItemProps,
  SidebarMenuSkeleton,
  type SidebarMenuSkeletonProps,
  SidebarMenuSub,
  type SidebarMenuSubProps,
  SidebarMenuSubButton,
  type SidebarMenuSubButtonProps,
  SidebarMenuSubItem,
  type SidebarMenuSubItemProps,
  SidebarProvider,
  type SidebarProviderProps,
  SidebarRail,
  type SidebarRailProps,
  SidebarSeparator,
  type SidebarSeparatorProps,
  SidebarTrigger,
  type SidebarTriggerProps,
  useSidebar,
} from "./Sidebar.tsx";
export { Skeleton, type SkeletonProps } from "./Skeleton.tsx";
export { Slider, type SliderProps } from "./Slider.tsx";
export { Spinner, type SpinnerProps } from "./Spinner.tsx";
export { Switch, type SwitchProps } from "./Switch.tsx";
export {
  Table,
  type TableProps,
  TableBody,
  type TableBodyProps,
  TableCaption,
  type TableCaptionProps,
  TableCell,
  type TableCellProps,
  TableFooter,
  type TableFooterProps,
  TableHead,
  type TableHeadProps,
  TableHeader,
  type TableHeaderProps,
  TableRow,
  type TableRowProps,
} from "./Table.tsx";
export {
  Tabs,
  type TabsProps,
  TabsContent,
  type TabsContentProps,
  TabsList,
  type TabsListProps,
  tabsListVariants,
  TabsTrigger,
  type TabsTriggerProps,
} from "./Tabs.tsx";
export { Textarea, type TextareaProps } from "./Textarea.tsx";
export { default as TimeAgo, type TimeAgoProps } from "./TimeAgo.tsx";
export { Toaster, type ToasterProps } from "./Toaster.tsx";
export {
  Tooltip,
  type TooltipProps,
  TooltipContent,
  type TooltipContentProps,
  TooltipProvider,
  type TooltipProviderProps,
  TooltipTrigger,
  type TooltipTriggerProps,
} from "./Tooltip.tsx";
export {
  type AlertOptions,
  type ConfirmOptions,
  DialogProvider,
  type DialogProviderProps,
  type PromptOptions,
  useDialog,
  useHasDialogProvider,
} from "./useDialog.tsx";
export { useIsMobile } from "./useIsMobile.ts";
export { UserAvatar, type UserAvatarProps } from "./UserAvatar.tsx";
export {
  type Toast,
  type ToastIntent,
  type ToastOptions,
  useToast,
} from "./useToast.tsx";
export { cn, formatBytes } from "./utils.ts";
